# Object Detection Project

## 1. Settings

In [6]:
from pathlib import Path

REPO_URL = "https://github.com/HoangDuonng1359/object-detection"
PROJECT_DIR = Path("/kaggle/working/object-detection")

IMAGE_SIZE = 640
EPOCHS = 30
BATCH_SIZE = 16
NUM_WORKERS = 2
LR = 1e-4
WEIGHT_DECAY = 1e-4
REG_MAX = 16
SMALL_OBJECT_MAX_SIDE = 96.0
MEDIUM_OBJECT_MAX_SIDE = 224.0
TAL_TOPK = 5
TAL_ALPHA = 0.5
TAL_BETA = 4.0
USE_AMP = True
DISABLE_TQDM = False
BACKBONE_NAME = "resnet101"  # "resnet50", "resnet101", "yolov8n", "yolov8s", or "yolov8m"
NECK_NAME = "yolov8_pan"  # "yolov8_pan" or "bifpn"
USE_PRETRAINED_BACKBONE = True
FREEZE_BACKBONE_STEM = False
OVERSAMPLE_CLASSES = ["chair"]
OVERSAMPLE_FACTOR = 2.0

# Set these to small values for a quick smoke test. Use 0 for full train/validation.
MAX_TRAIN_BATCHES = 0
MAX_VAL_BATCHES = 0

CONF_THRESHOLD = 0.25
# Tuned from validation: chair has low recall, car has room to trade precision for recall.
CLASS_THRESHOLDS = {
    "person": 0.35,
    "car": 0.25,
    "dog": 0.3,
    "cat": 0.3,
    "chair": 0.2,
}
CLASS_THRESHOLDS_TEXT = ",".join(f"{name}={value}" for name, value in CLASS_THRESHOLDS.items())
NMS_THRESHOLD = 0.35
MAX_DETECTIONS = 100

RUN_THRESHOLD_SWEEP = True
CLASS_THRESHOLD_CONFIGS = [
    {
        "name": "balanced",
        "default": 0.25,
        "thresholds": CLASS_THRESHOLDS,
    },
    {
        "name": "more_recall",
        "default": 0.20,
        "thresholds": {"person": 0.20, "car": 0.15, "dog": 0.20, "cat": 0.20, "chair": 0.08},
    },
    {
        "name": "clean",
        "default": 0.30,
        "thresholds": {"person": 0.30, "car": 0.25, "dog": 0.25, "cat": 0.30, "chair": 0.15},
    },
    {
        "name": "map_oriented",
        "default": 0.15,
        "thresholds": {"person": 0.15, "car": 0.15, "dog": 0.15, "cat": 0.15, "chair": 0.08},
    },
]
NMS_VALUES = [0.35, 0.45, 0.50]

# Optional hidden/test image directory. Leave as None if you only want val predictions.
TEST_IMAGE_DIR = None
FINAL_PREDICTIONS = Path("/kaggle/working/predictions.json")

## 2. Clone Code And Install Requirements

In [7]:
import os
import subprocess
import sys

if not PROJECT_DIR.exists():
    if "YOUR_USERNAME" in REPO_URL or "YOUR_REPO" in REPO_URL:
        raise ValueError("Edit REPO_URL in the settings cell before cloning.")
    clone_cmd = ["git", "clone"]
    clone_cmd += [REPO_URL, str(PROJECT_DIR)]
    subprocess.run(clone_cmd, check=True)
else:
    print(f"Project directory already exists: {PROJECT_DIR}")

os.chdir(PROJECT_DIR)
print("cwd:", Path.cwd())

requirements = PROJECT_DIR / "requirements.txt"
if requirements.exists():
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(requirements)], check=True)

import torch
print("python:", sys.version)
print("torch:", torch.__version__)
print("cuda_available:", torch.cuda.is_available())

Cloning into '/kaggle/working/object-detection'...

cwd: /kaggle/working/object-detection
python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
torch: 2.10.0+cu128
cuda_available: True

## 3. Locate Kaggle Input Dataset

In [8]:
PUBLIC_DIR = Path("/kaggle/input/datasets/duong1589/object-detection/public")
TRAIN_JSON = PUBLIC_DIR / "annotations" / "train.json"
VAL_JSON = PUBLIC_DIR / "annotations" / "val.json"
TRAIN_IMAGES = PUBLIC_DIR / "train" / "images"
VAL_IMAGES = PUBLIC_DIR / "val" / "images"
EVALUATOR = PUBLIC_DIR / "tools" / "evaluate_predictions.py"

print("PUBLIC_DIR:", PUBLIC_DIR)
print("TRAIN_JSON:", TRAIN_JSON)
print("VAL_JSON:", VAL_JSON)
print("TRAIN_IMAGES:", TRAIN_IMAGES)
print("VAL_IMAGES:", VAL_IMAGES)
print("EVALUATOR:", EVALUATOR, EVALUATOR.exists())

PUBLIC_DIR: /kaggle/input/datasets/duong1589/object-detection/public
TRAIN_JSON: /kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json
VAL_JSON: /kaggle/input/datasets/duong1589/object-detection/public/annotations/val.json
TRAIN_IMAGES: /kaggle/input/datasets/duong1589/object-detection/public/train/images
VAL_IMAGES: /kaggle/input/datasets/duong1589/object-detection/public/val/images
EVALUATOR: /kaggle/input/datasets/duong1589/object-detection/public/tools/evaluate_predictions.py True

## 4. Sanity Check Dataset And Code

In [9]:
import json

for split_name, json_path in [("train", TRAIN_JSON), ("val", VAL_JSON)]:
    data = json.loads(json_path.read_text(encoding="utf-8"))
    print(split_name, "images=", len(data["images"]), "annotations=", len(data["annotations"]))

subprocess.run([sys.executable, "-m", "py_compile", "train.py", "predict.py"], check=True)
subprocess.run([
    sys.executable, "-m", "utils.check_dataset",
    "--annotations", str(TRAIN_JSON),
    "--image_dir", str(TRAIN_IMAGES),
    "--image_size", str(IMAGE_SIZE),
    "--batch_size", "2",
    "--train",
], check=True)

train images= 7500 annotations= 10642
val images= 1500 annotations= 2021
dataset_size=7500
classes=['person', 'car', 'dog', 'cat', 'chair']
sample_image_shape=(3, 640, 640)
sample_image_id=img_000c52c6d12f.jpg
sample_boxes=(1, 4)
batch_image_shape=(2, 3, 640, 640)
batch_box_counts=[4, 2]

CompletedProcess(args=['/usr/bin/python3', '-m', 'utils.check_dataset', '--annotations', '/kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json', '--image_dir', '/kaggle/input/datasets/duong1589/object-detection/public/train/images', '--image_size', '640', '--batch_size', '2', '--train'], returncode=0)

## 5. Train

In [10]:
from IPython.display import display
import pandas as pd

train_cmd = [
    sys.executable, "train.py",
    "--train_data", str(TRAIN_JSON),
    "--val_data", str(VAL_JSON),
    "--image_dir", str(TRAIN_IMAGES),
    "--val_image_dir", str(VAL_IMAGES),
    "--checkpoint_dir", str(PROJECT_DIR / "models"),
    "--image_size", str(IMAGE_SIZE),
    "--epochs", str(EPOCHS),
    "--batch_size", str(BATCH_SIZE),
    "--num_workers", str(NUM_WORKERS),
    "--lr", str(LR),
    "--weight_decay", str(WEIGHT_DECAY),
    "--reg_max", str(REG_MAX),
    "--small_object_max_side", str(SMALL_OBJECT_MAX_SIDE),
    "--medium_object_max_side", str(MEDIUM_OBJECT_MAX_SIDE),
    "--tal_topk", str(TAL_TOPK),
    "--tal_alpha", str(TAL_ALPHA),
    "--tal_beta", str(TAL_BETA),
    "--backbone", BACKBONE_NAME,
    "--neck", NECK_NAME,
    "--conf_threshold", str(CONF_THRESHOLD),
    "--class_thresholds", CLASS_THRESHOLDS_TEXT,
    "--nms_threshold", str(NMS_THRESHOLD),
]
if DISABLE_TQDM:
    train_cmd.append("--disable_tqdm")
if USE_AMP:
    train_cmd.append("--amp")
if USE_PRETRAINED_BACKBONE:
    train_cmd.append("--pretrained_backbone")
if FREEZE_BACKBONE_STEM:
    train_cmd.append("--freeze_backbone_stem")
if OVERSAMPLE_CLASSES and OVERSAMPLE_FACTOR > 1.0:
    train_cmd += ["--oversample_classes", *OVERSAMPLE_CLASSES]
    train_cmd += ["--oversample_factor", str(OVERSAMPLE_FACTOR)]
if MAX_TRAIN_BATCHES > 0:
    train_cmd += ["--max_train_batches", str(MAX_TRAIN_BATCHES)]
if MAX_VAL_BATCHES > 0:
    train_cmd += ["--max_val_batches", str(MAX_VAL_BATCHES)]

print("Train command:")
print(" ".join(train_cmd))
subprocess.run(train_cmd, check=True)

history_files = sorted((PROJECT_DIR / "models").glob("train_history_*.csv"), key=lambda item: item.stat().st_mtime)
if history_files:
    HISTORY_CSV = history_files[-1]
    history_df = pd.read_csv(HISTORY_CSV)
    print("History CSV:", HISTORY_CSV)
    display_columns = [
        "epoch", "epoch_seconds", "train_seconds", "val_seconds", "lr",
        "train_loss", "val_loss", "val_map50", "val_micro_f1", "val_macro_f1",
        "best_map50", "best_val_loss", "best_micro_f1",
        "train_box_loss", "train_dfl_loss", "train_objectness_loss", "train_class_loss",
        "val_box_loss", "val_dfl_loss", "val_objectness_loss", "val_class_loss",
    ]
    display(history_df[[col for col in display_columns if col in history_df.columns]].tail(10))
else:
    HISTORY_CSV = None
    print("No train history CSV found.")

Train command:
/usr/bin/python3 train.py --train_data /kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json --val_data /kaggle/input/datasets/duong1589/object-detection/public/annotations/val.json --image_dir /kaggle/input/datasets/duong1589/object-detection/public/train/images --val_image_dir /kaggle/input/datasets/duong1589/object-detection/public/val/images --checkpoint_dir /kaggle/working/object-detection/models --image_size 640 --epochs 30 --batch_size 16 --num_workers 2 --lr 0.0001 --weight_decay 0.0001 --reg_max 16 --small_object_max_side 96.0 --medium_object_max_side 224.0 --tal_topk 5 --tal_alpha 0.5 --tal_beta 4.0 --backbone resnet101 --neck yolov8_pan --conf_threshold 0.25 --class_thresholds person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 --nms_threshold 0.35 --amp --pretrained_backbone --oversample_classes chair --oversample_factor 2.0
device=cuda amp=True
Downloading: "https://download.pytorch.org/models/resnet101-cd907fc2.pth" to /root/.cache/torch/hub/checkpoints/resnet101-cd907fc2.pth

100%|██████████| 171M/171M [00:00<00:00, 187MB/s]

class_thresholds: person=0.350, car=0.250, dog=0.300, cat=0.300, chair=0.200

epoch=1/30 epoch_time=10m08s train_time=8m38s val_time=1m24s lr=6.66667e-05 train_loss=10.0807 train_dfl=2.1716 val_loss=7.8494 val_dfl=1.6668 val_map50=0.2539 val_f1=0.4337 best_map50=0.2539 best_val_loss=7.8494 best_f1=0.4337

epoch=2/30 epoch_time=10m21s train_time=8m49s val_time=1m25s lr=0.0001 train_loss=6.2642 train_dfl=1.4213 val_loss=5.3507 val_dfl=1.2631 val_map50=0.5404 val_f1=0.6952 best_map50=0.5404 best_val_loss=5.3507 best_f1=0.6952

epoch=3/30 epoch_time=10m23s train_time=8m50s val_time=1m25s lr=0.0001 train_loss=4.6918 train_dfl=1.1566 val_loss=4.5536 val_dfl=1.1415 val_map50=0.5842 val_f1=0.7483 best_map50=0.5842 best_val_loss=4.5536 best_f1=0.7483

epoch=4/30 epoch_time=10m28s train_time=8m55s val_time=1m25s lr=9.96619e-05 train_loss=3.8366 train_dfl=1.0077 val_loss=4.2680 val_dfl=1.1065 val_map50=0.6456 val_f1=0.7645 best_map50=0.6456 best_val_loss=4.2680 best_f1=0.7645

epoch=5/30 epoch_time=10m27s train_time=8m56s val_time=1m26s lr=9.86522e-05 train_loss=3.3990 train_dfl=0.9289 val_loss=3.8808 val_dfl=1.0197 val_map50=0.7067 val_f1=0.7537 best_map50=0.7067 best_val_loss=3.8808 best_f1=0.7645

epoch=6/30 epoch_time=10m26s train_time=8m56s val_time=1m25s lr=9.69846e-05 train_loss=3.0666 train_dfl=0.8720 val_loss=3.7399 val_dfl=0.9988 val_map50=0.7037 val_f1=0.7830 best_map50=0.7067 best_val_loss=3.7399 best_f1=0.7830

epoch=7/30 epoch_time=10m20s train_time=8m53s val_time=1m26s lr=9.46816e-05 train_loss=2.8092 train_dfl=0.8229 val_loss=3.7629 val_dfl=1.0088 val_map50=0.6600 val_f1=0.7753 best_map50=0.7067 best_val_loss=3.7399 best_f1=0.7830

epoch=8/30 epoch_time=10m27s train_time=8m55s val_time=1m25s lr=9.17744e-05 train_loss=2.6637 train_dfl=0.7977 val_loss=3.5742 val_dfl=0.9753 val_map50=0.7100 val_f1=0.8002 best_map50=0.7100 best_val_loss=3.5742 best_f1=0.8002

epoch=9/30 epoch_time=10m18s train_time=8m51s val_time=1m26s lr=8.83022e-05 train_loss=2.4664 train_dfl=0.7581 val_loss=3.6644 val_dfl=1.0002 val_map50=0.7018 val_f1=0.7715 best_map50=0.7100 best_val_loss=3.5742 best_f1=0.8002

epoch=10/30 epoch_time=10m14s train_time=8m47s val_time=1m26s lr=8.43121e-05 train_loss=2.3540 train_dfl=0.7383 val_loss=3.6142 val_dfl=0.9801 val_map50=0.7053 val_f1=0.7916 best_map50=0.7100 best_val_loss=3.5742 best_f1=0.8002

epoch=11/30 epoch_time=10m24s train_time=8m54s val_time=1m25s lr=7.98579e-05 train_loss=2.2433 train_dfl=0.7154 val_loss=3.4825 val_dfl=0.9746 val_map50=0.7332 val_f1=0.8002 best_map50=0.7332 best_val_loss=3.4825 best_f1=0.8002

epoch=12/30 epoch_time=10m22s train_time=8m56s val_time=1m25s lr=7.5e-05 train_loss=2.1505 train_dfl=0.6971 val_loss=3.5730 val_dfl=0.9787 val_map50=0.6929 val_f1=0.7941 best_map50=0.7332 best_val_loss=3.4825 best_f1=0.8002

epoch=13/30 epoch_time=10m21s train_time=8m55s val_time=1m25s lr=6.9804e-05 train_loss=2.0354 train_dfl=0.6773 val_loss=3.4882 val_dfl=0.9643 val_map50=0.7102 val_f1=0.7955 best_map50=0.7332 best_val_loss=3.4825 best_f1=0.8002

epoch=14/30 epoch_time=10m21s train_time=8m53s val_time=1m25s lr=6.43402e-05 train_loss=1.9560 train_dfl=0.6622 val_loss=3.4658 val_dfl=0.9716 val_map50=0.7198 val_f1=0.7855 best_map50=0.7332 best_val_loss=3.4658 best_f1=0.8002

epoch=15/30 epoch_time=10m18s train_time=8m52s val_time=1m25s lr=5.86824e-05 train_loss=1.8871 train_dfl=0.6496 val_loss=3.4811 val_dfl=0.9619 val_map50=0.7082 val_f1=0.7962 best_map50=0.7332 best_val_loss=3.4658 best_f1=0.8002

epoch=16/30 epoch_time=10m24s train_time=8m55s val_time=1m25s lr=5.29072e-05 train_loss=1.8185 train_dfl=0.6384 val_loss=3.4371 val_dfl=0.9576 val_map50=0.7281 val_f1=0.8041 best_map50=0.7332 best_val_loss=3.4371 best_f1=0.8041

epoch=17/30 epoch_time=10m20s train_time=8m53s val_time=1m24s lr=4.70928e-05 train_loss=1.7743 train_dfl=0.6292 val_loss=3.4102 val_dfl=0.9473 val_map50=0.7074 val_f1=0.8012 best_map50=0.7332 best_val_loss=3.4102 best_f1=0.8041

epoch=18/30 epoch_time=10m23s train_time=8m56s val_time=1m24s lr=4.13176e-05 train_loss=1.7119 train_dfl=0.6195 val_loss=3.4174 val_dfl=0.9591 val_map50=0.7262 val_f1=0.8087 best_map50=0.7332 best_val_loss=3.4102 best_f1=0.8087

epoch=19/30 epoch_time=10m21s train_time=8m56s val_time=1m24s lr=3.56598e-05 train_loss=1.6310 train_dfl=0.6032 val_loss=3.4329 val_dfl=0.9619 val_map50=0.7201 val_f1=0.8075 best_map50=0.7332 best_val_loss=3.4102 best_f1=0.8087

epoch=20/30 epoch_time=10m23s train_time=8m53s val_time=1m24s lr=3.0196e-05 train_loss=1.5913 train_dfl=0.5977 val_loss=3.3476 val_dfl=0.9546 val_map50=0.7405 val_f1=0.8113 best_map50=0.7405 best_val_loss=3.3476 best_f1=0.8113

epoch=21/30 epoch_time=10m21s train_time=8m55s val_time=1m24s lr=2.5e-05 train_loss=1.5519 train_dfl=0.5915 val_loss=3.4092 val_dfl=0.9581 val_map50=0.7154 val_f1=0.8085 best_map50=0.7405 best_val_loss=3.3476 best_f1=0.8113

epoch=22/30 epoch_time=10m25s train_time=8m53s val_time=1m24s lr=2.01421e-05 train_loss=1.5162 train_dfl=0.5864 val_loss=3.3181 val_dfl=0.9534 val_map50=0.7452 val_f1=0.8133 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8133

epoch=23/30 epoch_time=10m19s train_time=8m53s val_time=1m24s lr=1.56879e-05 train_loss=1.4574 train_dfl=0.5753 val_loss=3.3581 val_dfl=0.9572 val_map50=0.7192 val_f1=0.8120 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8133

epoch=24/30 epoch_time=10m22s train_time=8m54s val_time=1m24s lr=1.16978e-05 train_loss=1.4241 train_dfl=0.5736 val_loss=3.3516 val_dfl=0.9597 val_map50=0.7246 val_f1=0.8139 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8139

epoch=25/30 epoch_time=10m22s train_time=8m56s val_time=1m24s lr=8.22561e-06 train_loss=1.3901 train_dfl=0.5668 val_loss=3.3662 val_dfl=0.9613 val_map50=0.7177 val_f1=0.8122 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8139

epoch=26/30 epoch_time=10m13s train_time=8m46s val_time=1m24s lr=5.31837e-06 train_loss=1.3470 train_dfl=0.5619 val_loss=3.3242 val_dfl=0.9616 val_map50=0.7406 val_f1=0.8184 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8184

epoch=27/30 epoch_time=10m21s train_time=8m54s val_time=1m24s lr=3.01537e-06 train_loss=1.3399 train_dfl=0.5596 val_loss=3.3493 val_dfl=0.9587 val_map50=0.7304 val_f1=0.8196 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8196

epoch=28/30 epoch_time=10m21s train_time=8m54s val_time=1m24s lr=1.34776e-06 train_loss=1.3315 train_dfl=0.5604 val_loss=3.3229 val_dfl=0.9557 val_map50=0.7387 val_f1=0.8197 best_map50=0.7452 best_val_loss=3.3181 best_f1=0.8197

epoch=29/30 epoch_time=10m21s train_time=8m54s val_time=1m24s lr=3.38082e-07 train_loss=1.3194 train_dfl=0.5577 val_loss=3.3163 val_dfl=0.9571 val_map50=0.7364 val_f1=0.8182 best_map50=0.7452 best_val_loss=3.3163 best_f1=0.8197

epoch=30/30 epoch_time=10m23s train_time=8m56s val_time=1m24s lr=0 train_loss=1.3197 train_dfl=0.5581 val_loss=3.3408 val_dfl=0.9587 val_map50=0.7363 val_f1=0.8220 best_map50=0.7452 best_val_loss=3.3163 best_f1=0.8220
best_map50_checkpoint=/kaggle/working/object-detection/models/best_map50.pth
best_val_loss_checkpoint=/kaggle/working/object-detection/models/best_val_loss.pth
best_f1_checkpoint=/kaggle/working/object-detection/models/best_f1.pth
best_checkpoint=/kaggle/working/object-detection/models/best.pth
history=/kaggle/working/object-detection/models/train_history_20260612_051946.csv
History CSV: /kaggle/working/object-detection/models/train_history_20260612_051946.csv

,epoch,epoch_seconds,train_seconds,val_seconds,lr,train_loss,val_loss,val_map50,val_micro_f1,val_macro_f1,...,best_val_loss,best_micro_f1,train_box_loss,train_dfl_loss,train_objectness_loss,train_class_loss,val_box_loss,val_dfl_loss,val_objectness_loss,val_class_loss
20,21,620.84,535.31,84.14,2.500000e-05,1.551913,3.409183,0.715384,0.808511,0.787825,...,3.347619,0.811272,0.053632,0.591503,0.0,0.524840,0.143649,0.958113,0.0,1.789289
21,22,624.70,533.45,84.49,2.014207e-05,1.516186,3.318140,0.745231,0.813299,0.795295,...,3.318140,0.813299,0.051275,0.586448,0.0,0.503906,0.141271,0.953420,0.0,1.656954
22,23,619.20,533.38,84.39,1.568792e-05,1.457426,3.358081,0.719210,0.812034,0.791467,...,3.318140,0.813299,0.047785,0.575294,0.0,0.472200,0.140850,0.957198,0.0,1.731815
23,24,621.73,534.31,84.42,1.169778e-05,1.424082,3.351620,0.724580,0.813873,0.791425,...,3.318140,0.813873,0.045286,0.573605,0.0,0.448061,0.141481,0.959723,0.0,1.701856
24,25,621.74,535.95,84.24,8.225609e-06,1.390126,3.366192,0.717726,0.812215,0.793775,...,3.318140,0.813873,0.042951,0.566780,0.0,0.435651,0.140972,0.961289,0.0,1.733940
25,26,612.66,525.93,84.10,5.318368e-06,1.347031,3.324205,0.740604,0.818396,0.798596,...,3.318140,0.818396,0.039906,0.561851,0.0,0.409913,0.139835,0.961575,0.0,1.666161
26,27,621.05,534.04,84.18,3.015369e-06,1.339896,3.349259,0.730401,0.819603,0.798996,...,3.318140,0.819603,0.039711,0.559620,0.0,0.405265,0.140433,0.958740,0.0,1.715800
27,28,621.45,534.39,84.20,1.347756e-06,1.331536,3.322889,0.738711,0.819664,0.801369,...,3.318140,0.819664,0.038796,0.560419,0.0,0.399873,0.139432,0.955726,0.0,1.687117
28,29,621.36,533.91,84.33,3.380821e-07,1.319435,3.316254,0.736427,0.818206,0.797685,...,3.316254,0.819664,0.038151,0.557662,0.0,0.393622,0.139374,0.957099,0.0,1.670607
29,30,623.11,536.04,84.24,0.000000e+00,1.319672,3.340838,0.736261,0.822034,0.802409,...,3.316254,0.822034,0.038286,0.558130,0.0,0.390657,0.140078,0.958703,0.0,1.704397

## 6. Predict On Validation And Evaluate

In [11]:
VAL_PREDICTIONS = PROJECT_DIR / "val_predictions.json"
predict_val_cmd = [
    sys.executable, "predict.py",
    "--image_dir", str(VAL_IMAGES),
    "--output", str(VAL_PREDICTIONS),
    "--checkpoint", str(PROJECT_DIR / "models" / "best.pth"),
    "--batch_size", str(BATCH_SIZE),
    "--conf_threshold", str(CONF_THRESHOLD),
    "--class_thresholds", CLASS_THRESHOLDS_TEXT,
    "--nms_threshold", str(NMS_THRESHOLD),
    "--max_detections", str(MAX_DETECTIONS),
]
print("Predict validation command:")
print(" ".join(predict_val_cmd))
subprocess.run(predict_val_cmd, check=True)

val_predictions_data = json.loads(VAL_PREDICTIONS.read_text(encoding="utf-8"))
num_pred_boxes = sum(len(item["boxes"]) for item in val_predictions_data)
print(f"Validation predictions: images={len(val_predictions_data)} boxes={num_pred_boxes}")
print("Prediction preview:")
print(json.dumps(val_predictions_data[:3], ensure_ascii=False, indent=2))

if EVALUATOR.exists():
    VAL_SCORE = PROJECT_DIR / "val_score.json"
    subprocess.run([
        sys.executable, str(EVALUATOR),
        "--ground_truth", str(VAL_JSON),
        "--predictions", str(VAL_PREDICTIONS),
        "--output", str(VAL_SCORE),
    ], check=True)
    score = json.loads(VAL_SCORE.read_text(encoding="utf-8"))
    print("Validation score:")
    print(json.dumps(score, ensure_ascii=False, indent=2))
    if "per_class" in score:
        per_class_df = pd.DataFrame.from_dict(score["per_class"], orient="index")
        display(per_class_df)
else:
    VAL_SCORE = None
    print("Evaluator not found, skipped local validation scoring.")

Predict validation command:
/usr/bin/python3 predict.py --image_dir /kaggle/input/datasets/duong1589/object-detection/public/val/images --output /kaggle/working/object-detection/val_predictions.json --checkpoint /kaggle/working/object-detection/models/best.pth --batch_size 16 --conf_threshold 0.25 --class_thresholds person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 --nms_threshold 0.35 --max_detections 100
wrote 1500 predictions to /kaggle/working/object-detection/val_predictions.json
Validation predictions: images=1500 boxes=1889
Prediction preview:
[
  {
    "image_id": "img_00090df9158f.jpg",
    "boxes": [
      {
        "class": "cat",
        "confidence": 0.73643,
        "bbox": [
          132.07,
          40.02,
          499.3,
          375.0
        ]
      },
      {
        "class": "dog",
        "confidence": 0.348,
        "bbox": [
          131.92,
          31.92,
          500.0,
          374.99
        ]
      }
    ]
  },
  {
    "image_id": "img_003c3ddc6a82.jpg",
    "boxes": []
  },
  {
    "image_id": "img_01073356e41c.jpg",
    "boxes": [
      {
        "class": "person",
        "confidence": 0.459667,
        "bbox": [
          389.59,
          12.74,
          468.92,
          135.42
        ]
      }
    ]
  }
]
{
  "mAP@0.5": 0.745231,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1889,
  "micro_precision": 0.841715,
  "micro_recall": 0.786739,
  "per_class": {
    "person": {
      "ap": 0.820101,
      "num_ground_truth": 1074,
      "num_predictions": 1007,
      "true_positives": 893,
      "false_positives": 114,
      "recall": 0.831471,
      "precision": 0.886792
    },
    "car": {
      "ap": 0.734483,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.814944,
      "num_ground_truth": 206,
      "num_predictions": 193,
      "true_positives": 170,
      "false_positives": 23,
      "recall": 0.825243,
      "precision": 0.880829
    },
    "cat": {
      "ap": 0.842804,
      "num_ground_truth": 176,
      "num_predictions": 165,
      "true_positives": 150,
      "false_positives": 15,
      "recall": 0.852273,
      "precision": 0.909091
    },
    "chair": {
      "ap": 0.513825,
      "num_ground_truth": 282,
      "num_predictions": 267,
      "true_positives": 164,
      "false_positives": 103,
      "recall": 0.58156,
      "precision": 0.614232
    }
  }
}
Validation score:
{
  "mAP@0.5": 0.745231,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1889,
  "micro_precision": 0.841715,
  "micro_recall": 0.786739,
  "per_class": {
    "person": {
      "ap": 0.820101,
      "num_ground_truth": 1074,
      "num_predictions": 1007,
      "true_positives": 893,
      "false_positives": 114,
      "recall": 0.831471,
      "precision": 0.886792
    },
    "car": {
      "ap": 0.734483,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.814944,
      "num_ground_truth": 206,
      "num_predictions": 193,
      "true_positives": 170,
      "false_positives": 23,
      "recall": 0.825243,
      "precision": 0.880829
    },
    "cat": {
      "ap": 0.842804,
      "num_ground_truth": 176,
      "num_predictions": 165,
      "true_positives": 150,
      "false_positives": 15,
      "recall": 0.852273,
      "precision": 0.909091
    },
    "chair": {
      "ap": 0.513825,
      "num_ground_truth": 282,
      "num_predictions": 267,
      "true_positives": 164,
      "false_positives": 103,
      "recall": 0.58156,
      "precision": 0.614232
    }
  }
}

,ap,num_ground_truth,num_predictions,true_positives,false_positives,recall,precision
person,0.820101,1074,1007,893,114,0.831471,0.886792
car,0.734483,283,257,213,44,0.752650,0.828794
dog,0.814944,206,193,170,23,0.825243,0.880829
cat,0.842804,176,165,150,15,0.852273,0.909091
chair,0.513825,282,267,164,103,0.581560,0.614232

## 7. Threshold Sweep On Validation

In [12]:
import json
import pandas as pd

BEST_CHECKPOINT = PROJECT_DIR / "models" / "best.pth"

def thresholds_to_text(thresholds):
    return ",".join(f"{name}={value}" for name, value in thresholds.items())

if RUN_THRESHOLD_SWEEP:
    if not (VAL_JSON.exists() and EVALUATOR.exists()):
        raise FileNotFoundError("Need VAL_JSON and EVALUATOR for threshold sweep.")
    rows = []
    sweep_dir = PROJECT_DIR / "threshold_sweep"
    sweep_dir.mkdir(parents=True, exist_ok=True)
    for config in CLASS_THRESHOLD_CONFIGS:
        config_name = config["name"]
        default_conf = config["default"]
        thresholds = config["thresholds"]
        thresholds_text = thresholds_to_text(thresholds)
        safe_thresholds = thresholds_text.replace(",", "_").replace("=", "-")
        for nms in NMS_VALUES:
            sweep_pred = sweep_dir / f"predictions_{config_name}_nms{nms:.2f}_{safe_thresholds}.json"
            sweep_score = sweep_dir / f"score_{config_name}_nms{nms:.2f}_{safe_thresholds}.json"
            print(f"Running config={config_name} default={default_conf:.2f} thresholds={thresholds_text} nms={nms:.2f}")
            !{sys.executable} predict.py --image_dir "{VAL_IMAGES}" --output "{sweep_pred}" --checkpoint "{BEST_CHECKPOINT}" --batch_size {BATCH_SIZE} --conf_threshold {default_conf} --class_thresholds "{thresholds_text}" --nms_threshold {nms} --max_detections {MAX_DETECTIONS}
            !{sys.executable} "{EVALUATOR}" --ground_truth "{VAL_JSON}" --predictions "{sweep_pred}" --output "{sweep_score}"
            score = json.loads(sweep_score.read_text(encoding="utf-8"))
            per_class = score.get("per_class", {})
            chair = per_class.get("chair", {})
            rows.append({
                "config": config_name,
                "thresholds": thresholds_text,
                "default_conf": default_conf,
                "nms": nms,
                "map50": score.get("mAP@0.5", 0.0),
                "performance_points": score.get("performance_points", 0),
                "precision": score.get("micro_precision", 0.0),
                "recall": score.get("micro_recall", 0.0),
                "num_predictions": score.get("num_predictions", 0),
                "chair_ap": chair.get("ap", 0.0),
                "chair_precision": chair.get("precision", 0.0),
                "chair_recall": chair.get("recall", 0.0),
            })
    sweep_df = pd.DataFrame(rows).sort_values(["map50", "precision"], ascending=[False, False])
    sweep_csv = sweep_dir / "threshold_sweep_results.csv"
    sweep_df.to_csv(sweep_csv, index=False)
    print("Threshold sweep results:", sweep_csv)
    display(sweep_df)
else:
    print("Threshold sweep disabled. Set RUN_THRESHOLD_SWEEP = True to run it.")

Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.35_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.745231,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1889,
  "micro_precision": 0.841715,
  "micro_recall": 0.786739,
  "per_class": {
    "person": {
      "ap": 0.820101,
      "num_ground_truth": 1074,
      "num_predictions": 1007,
      "true_positives": 893,
      "false_positives": 114,
      "recall": 0.831471,
      "precision": 0.886792
    },
    "car": {
      "ap": 0.734483,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.814944,
      "num_ground_truth": 206,
      "num_predictions": 193,
      "true_positives": 170,
      "false_positives": 23,
      "recall": 0.825243,
      "precision": 0.880829
    },
    "cat": {
      "ap": 0.842804,
      "num_ground_truth": 176,
      "num_predictions": 165,
      "true_positives": 150,
      "false_positives": 15,
      "recall": 0.852273,
      "precision": 0.909091
    },
    "chair": {
      "ap": 0.513825,
      "num_ground_truth": 282,
      "num_predictions": 267,
      "true_positives": 164,
      "false_positives": 103,
      "recall": 0.58156,
      "precision": 0.614232
    }
  }
}
Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.45_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.747765,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1915,
  "micro_precision": 0.834987,
  "micro_recall": 0.791192,
  "per_class": {
    "person": {
      "ap": 0.826168,
      "num_ground_truth": 1074,
      "num_predictions": 1024,
      "true_positives": 900,
      "false_positives": 124,
      "recall": 0.837989,
      "precision": 0.878906
    },
    "car": {
      "ap": 0.734723,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.819331,
      "num_ground_truth": 206,
      "num_predictions": 195,
      "true_positives": 171,
      "false_positives": 24,
      "recall": 0.830097,
      "precision": 0.876923
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 166,
      "true_positives": 150,
      "false_positives": 16,
      "recall": 0.852273,
      "precision": 0.903614
    },
    "chair": {
      "ap": 0.515832,
      "num_ground_truth": 282,
      "num_predictions": 273,
      "true_positives": 165,
      "false_positives": 108,
      "recall": 0.585106,
      "precision": 0.604396
    }
  }
}
Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.50_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.748652,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1928,
  "micro_precision": 0.830913,
  "micro_recall": 0.792677,
  "per_class": {
    "person": {
      "ap": 0.827755,
      "num_ground_truth": 1074,
      "num_predictions": 1032,
      "true_positives": 902,
      "false_positives": 130,
      "recall": 0.839851,
      "precision": 0.874031
    },
    "car": {
      "ap": 0.737782,
      "num_ground_truth": 283,
      "num_predictions": 260,
      "true_positives": 214,
      "false_positives": 46,
      "recall": 0.756184,
      "precision": 0.823077
    },
    "dog": {
      "ap": 0.819331,
      "num_ground_truth": 206,
      "num_predictions": 195,
      "true_positives": 171,
      "false_positives": 24,
      "recall": 0.830097,
      "precision": 0.876923
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 166,
      "true_positives": 150,
      "false_positives": 16,
      "recall": 0.852273,
      "precision": 0.903614
    },
    "chair": {
      "ap": 0.515621,
      "num_ground_truth": 282,
      "num_predictions": 275,
      "true_positives": 165,
      "false_positives": 110,
      "recall": 0.585106,
      "precision": 0.6
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.35_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.755275,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2008,
  "micro_precision": 0.806275,
  "micro_recall": 0.801089,
  "per_class": {
    "person": {
      "ap": 0.832342,
      "num_ground_truth": 1074,
      "num_predictions": 1060,
      "true_positives": 908,
      "false_positives": 152,
      "recall": 0.845438,
      "precision": 0.856604
    },
    "car": {
      "ap": 0.748963,
      "num_ground_truth": 283,
      "num_predictions": 270,
      "true_positives": 218,
      "false_positives": 52,
      "recall": 0.770318,
      "precision": 0.807407
    },
    "dog": {
      "ap": 0.823483,
      "num_ground_truth": 206,
      "num_predictions": 196,
      "true_positives": 172,
      "false_positives": 24,
      "recall": 0.834951,
      "precision": 0.877551
    },
    "cat": {
      "ap": 0.842804,
      "num_ground_truth": 176,
      "num_predictions": 168,
      "true_positives": 150,
      "false_positives": 18,
      "recall": 0.852273,
      "precision": 0.892857
    },
    "chair": {
      "ap": 0.528783,
      "num_ground_truth": 282,
      "num_predictions": 314,
      "true_positives": 171,
      "false_positives": 143,
      "recall": 0.606383,
      "precision": 0.544586
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.45_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.758716,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2043,
  "micro_precision": 0.798336,
  "micro_recall": 0.807026,
  "per_class": {
    "person": {
      "ap": 0.83911,
      "num_ground_truth": 1074,
      "num_predictions": 1081,
      "true_positives": 916,
      "false_positives": 165,
      "recall": 0.852886,
      "precision": 0.847364
    },
    "car": {
      "ap": 0.749117,
      "num_ground_truth": 283,
      "num_predictions": 272,
      "true_positives": 218,
      "false_positives": 54,
      "recall": 0.770318,
      "precision": 0.801471
    },
    "dog": {
      "ap": 0.827789,
      "num_ground_truth": 206,
      "num_predictions": 199,
      "true_positives": 173,
      "false_positives": 26,
      "recall": 0.839806,
      "precision": 0.869347
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 169,
      "true_positives": 150,
      "false_positives": 19,
      "recall": 0.852273,
      "precision": 0.887574
    },
    "chair": {
      "ap": 0.534796,
      "num_ground_truth": 282,
      "num_predictions": 322,
      "true_positives": 174,
      "false_positives": 148,
      "recall": 0.617021,
      "precision": 0.540373
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.50_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.75969,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2061,
  "micro_precision": 0.793304,
  "micro_recall": 0.809005,
  "per_class": {
    "person": {
      "ap": 0.841428,
      "num_ground_truth": 1074,
      "num_predictions": 1091,
      "true_positives": 919,
      "false_positives": 172,
      "recall": 0.85568,
      "precision": 0.842346
    },
    "car": {
      "ap": 0.752018,
      "num_ground_truth": 283,
      "num_predictions": 277,
      "true_positives": 219,
      "false_positives": 58,
      "recall": 0.773852,
      "precision": 0.790614
    },
    "dog": {
      "ap": 0.827789,
      "num_ground_truth": 206,
      "num_predictions": 199,
      "true_positives": 173,
      "false_positives": 26,
      "recall": 0.839806,
      "precision": 0.869347
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 169,
      "true_positives": 150,
      "false_positives": 19,
      "recall": 0.852273,
      "precision": 0.887574
    },
    "chair": {
      "ap": 0.534444,
      "num_ground_truth": 282,
      "num_predictions": 325,
      "true_positives": 174,
      "false_positives": 151,
      "recall": 0.617021,
      "precision": 0.535385
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.35_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.748395,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1919,
  "micro_precision": 0.834289,
  "micro_recall": 0.792182,
  "per_class": {
    "person": {
      "ap": 0.825048,
      "num_ground_truth": 1074,
      "num_predictions": 1023,
      "true_positives": 899,
      "false_positives": 124,
      "recall": 0.837058,
      "precision": 0.878788
    },
    "car": {
      "ap": 0.734483,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.814944,
      "num_ground_truth": 206,
      "num_predictions": 193,
      "true_positives": 170,
      "false_positives": 23,
      "recall": 0.825243,
      "precision": 0.880829
    },
    "cat": {
      "ap": 0.842804,
      "num_ground_truth": 176,
      "num_predictions": 165,
      "true_positives": 150,
      "false_positives": 15,
      "recall": 0.852273,
      "precision": 0.909091
    },
    "chair": {
      "ap": 0.524697,
      "num_ground_truth": 282,
      "num_predictions": 281,
      "true_positives": 169,
      "false_positives": 112,
      "recall": 0.599291,
      "precision": 0.601423
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.45_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.751325,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1947,
  "micro_precision": 0.827427,
  "micro_recall": 0.79713,
  "per_class": {
    "person": {
      "ap": 0.831072,
      "num_ground_truth": 1074,
      "num_predictions": 1040,
      "true_positives": 906,
      "false_positives": 134,
      "recall": 0.843575,
      "precision": 0.871154
    },
    "car": {
      "ap": 0.734723,
      "num_ground_truth": 283,
      "num_predictions": 257,
      "true_positives": 213,
      "false_positives": 44,
      "recall": 0.75265,
      "precision": 0.828794
    },
    "dog": {
      "ap": 0.819331,
      "num_ground_truth": 206,
      "num_predictions": 196,
      "true_positives": 171,
      "false_positives": 25,
      "recall": 0.830097,
      "precision": 0.872449
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 166,
      "true_positives": 150,
      "false_positives": 16,
      "recall": 0.852273,
      "precision": 0.903614
    },
    "chair": {
      "ap": 0.528728,
      "num_ground_truth": 282,
      "num_predictions": 288,
      "true_positives": 171,
      "false_positives": 117,
      "recall": 0.606383,
      "precision": 0.59375
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.50_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.752188,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1961,
  "micro_precision": 0.823049,
  "micro_recall": 0.798615,
  "per_class": {
    "person": {
      "ap": 0.832631,
      "num_ground_truth": 1074,
      "num_predictions": 1049,
      "true_positives": 908,
      "false_positives": 141,
      "recall": 0.845438,
      "precision": 0.865586
    },
    "car": {
      "ap": 0.737782,
      "num_ground_truth": 283,
      "num_predictions": 260,
      "true_positives": 214,
      "false_positives": 46,
      "recall": 0.756184,
      "precision": 0.823077
    },
    "dog": {
      "ap": 0.819331,
      "num_ground_truth": 206,
      "num_predictions": 196,
      "true_positives": 171,
      "false_positives": 25,
      "recall": 0.830097,
      "precision": 0.872449
    },
    "cat": {
      "ap": 0.842769,
      "num_ground_truth": 176,
      "num_predictions": 166,
      "true_positives": 150,
      "false_positives": 16,
      "recall": 0.852273,
      "precision": 0.903614
    },
    "chair": {
      "ap": 0.528428,
      "num_ground_truth": 282,
      "num_predictions": 290,
      "true_positives": 171,
      "false_positives": 119,
      "recall": 0.606383,
      "precision": 0.589655
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.35_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.757553,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2040,
  "micro_precision": 0.798039,
  "micro_recall": 0.805542,
  "per_class": {
    "person": {
      "ap": 0.838654,
      "num_ground_truth": 1074,
      "num_predictions": 1088,
      "true_positives": 916,
      "false_positives": 172,
      "recall": 0.852886,
      "precision": 0.841912
    },
    "car": {
      "ap": 0.748963,
      "num_ground_truth": 283,
      "num_predictions": 270,
      "true_positives": 218,
      "false_positives": 52,
      "recall": 0.770318,
      "precision": 0.807407
    },
    "dog": {
      "ap": 0.823483,
      "num_ground_truth": 206,
      "num_predictions": 198,
      "true_positives": 172,
      "false_positives": 26,
      "recall": 0.834951,
      "precision": 0.868687
    },
    "cat": {
      "ap": 0.84788,
      "num_ground_truth": 176,
      "num_predictions": 170,
      "true_positives": 151,
      "false_positives": 19,
      "recall": 0.857955,
      "precision": 0.888235
    },
    "chair": {
      "ap": 0.528783,
      "num_ground_truth": 282,
      "num_predictions": 314,
      "true_positives": 171,
      "false_positives": 143,
      "recall": 0.606383,
      "precision": 0.544586
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.45_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.76166,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2079,
  "micro_precision": 0.788841,
  "micro_recall": 0.811479,
  "per_class": {
    "person": {
      "ap": 0.844577,
      "num_ground_truth": 1074,
      "num_predictions": 1112,
      "true_positives": 923,
      "false_positives": 189,
      "recall": 0.859404,
      "precision": 0.830036
    },
    "car": {
      "ap": 0.749117,
      "num_ground_truth": 283,
      "num_predictions": 272,
      "true_positives": 218,
      "false_positives": 54,
      "recall": 0.770318,
      "precision": 0.801471
    },
    "dog": {
      "ap": 0.831991,
      "num_ground_truth": 206,
      "num_predictions": 202,
      "true_positives": 174,
      "false_positives": 28,
      "recall": 0.84466,
      "precision": 0.861386
    },
    "cat": {
      "ap": 0.847816,
      "num_ground_truth": 176,
      "num_predictions": 171,
      "true_positives": 151,
      "false_positives": 20,
      "recall": 0.857955,
      "precision": 0.883041
    },
    "chair": {
      "ap": 0.534796,
      "num_ground_truth": 282,
      "num_predictions": 322,
      "true_positives": 174,
      "false_positives": 148,
      "recall": 0.617021,
      "precision": 0.540373
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.50_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.762776,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2099,
  "micro_precision": 0.783707,
  "micro_recall": 0.813953,
  "per_class": {
    "person": {
      "ap": 0.847631,
      "num_ground_truth": 1074,
      "num_predictions": 1123,
      "true_positives": 927,
      "false_positives": 196,
      "recall": 0.863128,
      "precision": 0.825467
    },
    "car": {
      "ap": 0.752018,
      "num_ground_truth": 283,
      "num_predictions": 277,
      "true_positives": 219,
      "false_positives": 58,
      "recall": 0.773852,
      "precision": 0.790614
    },
    "dog": {
      "ap": 0.831971,
      "num_ground_truth": 206,
      "num_predictions": 203,
      "true_positives": 174,
      "false_positives": 29,
      "recall": 0.84466,
      "precision": 0.857143
    },
    "cat": {
      "ap": 0.847816,
      "num_ground_truth": 176,
      "num_predictions": 171,
      "true_positives": 151,
      "false_positives": 20,
      "recall": 0.857955,
      "precision": 0.883041
    },
    "chair": {
      "ap": 0.534444,
      "num_ground_truth": 282,
      "num_predictions": 325,
      "true_positives": 174,
      "false_positives": 151,
      "recall": 0.617021,
      "precision": 0.535385
    }
  }
}
Threshold sweep results: /kaggle/working/object-detection/threshold_sweep/threshold_sweep_results.csv

,config,thresholds,default_conf,nms,map50,performance_points,precision,recall,num_predictions,chair_ap,chair_precision,chair_recall
11,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.50,0.762776,20,0.783707,0.813953,2099,0.534444,0.535385,0.617021
10,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.45,0.761660,20,0.788841,0.811479,2079,0.534796,0.540373,0.617021
5,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.50,0.759690,20,0.793304,0.809005,2061,0.534444,0.535385,0.617021
4,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.45,0.758716,20,0.798336,0.807026,2043,0.534796,0.540373,0.617021
9,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.35,0.757553,20,0.798039,0.805542,2040,0.528783,0.544586,0.606383
3,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.35,0.755275,20,0.806275,0.801089,2008,0.528783,0.544586,0.606383
8,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.50,0.752188,20,0.823049,0.798615,1961,0.528428,0.589655,0.606383
7,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.45,0.751325,20,0.827427,0.797130,1947,0.528728,0.593750,0.606383
2,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.50,0.748652,20,0.830913,0.792677,1928,0.515621,0.600000,0.585106
6,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.35,0.748395,20,0.834289,0.792182,1919,0.524697,0.601423,0.599291
1,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.45,0.747765,20,0.834987,0.791192,1915,0.515832,0.604396,0.585106
0,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.35,0.745231,20,0.841715,0.786739,1889,0.513825,0.614232,0.581560

## 8. Predict On Hidden/Test Images If Available

In [13]:
if TEST_IMAGE_DIR is None:
    print("TEST_IMAGE_DIR is None. Skipped final prediction.")
else:
    test_dir = Path(TEST_IMAGE_DIR)
    final_cmd = [
        sys.executable, "predict.py",
        "--image_dir", str(test_dir),
        "--output", str(FINAL_PREDICTIONS),
        "--checkpoint", str(PROJECT_DIR / "models" / "best.pth"),
        "--batch_size", str(BATCH_SIZE),
        "--conf_threshold", str(CONF_THRESHOLD),
        "--class_thresholds", CLASS_THRESHOLDS_TEXT,
        "--nms_threshold", str(NMS_THRESHOLD),
    ]
    print("Final predict command:")
    print(" ".join(final_cmd))
    subprocess.run(final_cmd, check=True)
    final_data = json.loads(FINAL_PREDICTIONS.read_text(encoding="utf-8"))
    print(f"Final predictions: images={len(final_data)} boxes={sum(len(item['boxes']) for item in final_data)}")
    print("Final prediction preview:")
    print(json.dumps(final_data[:3], ensure_ascii=False, indent=2))
    print("Final predictions path:", FINAL_PREDICTIONS)

TEST_IMAGE_DIR is None. Skipped final prediction.

## 9. Collect Artifacts

In [14]:
import shutil

ARTIFACT_DIR = Path("/kaggle/working/artifacts")
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

files_to_copy = [
    PROJECT_DIR / "models" / "best_map50.pth",
    PROJECT_DIR / "models" / "best_val_loss.pth",
    PROJECT_DIR / "models" / "best_f1.pth",
    PROJECT_DIR / "models" / "best.pth",
    PROJECT_DIR / "models" / "last.pth",
    VAL_PREDICTIONS,
    PROJECT_DIR / "val_score.json",
]
files_to_copy += sorted((PROJECT_DIR / "models").glob("train_history_*.csv"))
sweep_results = PROJECT_DIR / "threshold_sweep" / "threshold_sweep_results.csv"
if sweep_results.exists():
    files_to_copy.append(sweep_results)
if FINAL_PREDICTIONS.exists():
    files_to_copy.append(FINAL_PREDICTIONS)

copied = []
for src in files_to_copy:
    if src.exists():
        dst = ARTIFACT_DIR / src.name
        shutil.copy2(src, dst)
        copied.append(dst)

zip_path = shutil.make_archive("/kaggle/working/object_detection_artifacts", "zip", ARTIFACT_DIR)
print("Artifacts directory:", ARTIFACT_DIR)
print("Artifacts zip:", zip_path)
print("Files:")
artifact_rows = []
for path in sorted(ARTIFACT_DIR.iterdir()):
    artifact_rows.append({"file": path.name, "size_mb": round(path.stat().st_size / (1024 * 1024), 3)})
display(pd.DataFrame(artifact_rows))

Artifacts directory: /kaggle/working/artifacts
Artifacts zip: /kaggle/working/object_detection_artifacts.zip
Files:

                                file  size_mb
0                           best.pth  647.299
1                        best_f1.pth  647.409
2                     best_map50.pth  647.416
3                  best_val_loss.pth  647.423
4                           last.pth  647.299
5        threshold_sweep_results.csv    0.002
6  train_history_20260612_051946.csv    0.026
7               val_predictions.json    0.406
8                     val_score.json    0.001

## 10. Summary Shown In Notebook

In [15]:
summary = {
    "best_checkpoint": str(PROJECT_DIR / "models" / "best.pth"),
    "best_map50_checkpoint": str(PROJECT_DIR / "models" / "best_map50.pth"),
    "best_val_loss_checkpoint": str(PROJECT_DIR / "models" / "best_val_loss.pth"),
    "best_f1_checkpoint": str(PROJECT_DIR / "models" / "best_f1.pth"),
    "history_csv": str(HISTORY_CSV) if HISTORY_CSV is not None else None,
    "val_predictions": str(VAL_PREDICTIONS),
    "val_score": str(PROJECT_DIR / "val_score.json"),
    "threshold_sweep_results": str(PROJECT_DIR / "threshold_sweep" / "threshold_sweep_results.csv"),
    "artifacts_zip": "/kaggle/working/object_detection_artifacts.zip",
}
print(json.dumps(summary, ensure_ascii=False, indent=2))

if HISTORY_CSV is not None:
    history_df = pd.read_csv(HISTORY_CSV)
    print("Final history row:")
    display(history_df.tail(1))

score_path = PROJECT_DIR / "val_score.json"
if score_path.exists():
    score = json.loads(score_path.read_text(encoding="utf-8"))
    print(f"mAP@0.5={score.get('mAP@0.5')} performance_points={score.get('performance_points')}")

{
  "best_checkpoint": "/kaggle/working/object-detection/models/best.pth",
  "best_map50_checkpoint": "/kaggle/working/object-detection/models/best_map50.pth",
  "best_val_loss_checkpoint": "/kaggle/working/object-detection/models/best_val_loss.pth",
  "best_f1_checkpoint": "/kaggle/working/object-detection/models/best_f1.pth",
  "history_csv": "/kaggle/working/object-detection/models/train_history_20260612_051946.csv",
  "val_predictions": "/kaggle/working/object-detection/val_predictions.json",
  "val_score": "/kaggle/working/object-detection/val_score.json",
  "threshold_sweep_results": "/kaggle/working/object-detection/threshold_sweep/threshold_sweep_results.csv",
  "artifacts_zip": "/kaggle/working/object_detection_artifacts.zip"
}
Final history row:

,run_started_at,epoch,total_epochs,train_data,val_data,image_dir,val_image_dir,image_size,batch_size,num_workers,...,val_class_loss,val_num_positive,val_map50,val_micro_precision,val_micro_recall,val_micro_f1,val_macro_f1,best_map50,best_val_loss,best_micro_f1
29,2026-06-12 05:19:46,30,30,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,640,16,2,...,1.704397,105.244681,0.736261,0.88433,0.767937,0.822034,0.802409,0.745231,3.316254,0.822034

mAP@0.5=0.745231 performance_points=20