# Object Detection Project

## 1. Settings

In [1]:
from pathlib import Path

REPO_URL = "https://github.com/HoangDuonng1359/object-detection"
PROJECT_DIR = Path("/kaggle/working/object-detection")

IMAGE_SIZE = 640
EPOCHS = 30
BATCH_SIZE = 16
NUM_WORKERS = 2
LR = 1e-4
WEIGHT_DECAY = 1e-4
REG_MAX = 16
SMALL_OBJECT_MAX_SIDE = 96.0
MEDIUM_OBJECT_MAX_SIDE = 224.0
TAL_TOPK = 5
TAL_ALPHA = 0.5
TAL_BETA = 4.0
USE_AMP = True
DISABLE_TQDM = True
BACKBONE_NAME = "resnet50"  # "resnet50", "resnet101", "yolov8n", "yolov8s", or "yolov8m"
NECK_NAME = "yolov8_pan"  # "yolov8_pan" or "bifpn"
USE_PRETRAINED_BACKBONE = True
FREEZE_BACKBONE_STEM = False
OVERSAMPLE_CLASSES = ["chair"]
OVERSAMPLE_FACTOR = 2.0

# Set these to small values for a quick smoke test. Use 0 for full train/validation.
MAX_TRAIN_BATCHES = 0
MAX_VAL_BATCHES = 0

CONF_THRESHOLD = 0.25
# Tuned from validation: chair has low recall, car has room to trade precision for recall.
CLASS_THRESHOLDS = {
    "person": 0.35,
    "car": 0.25,
    "dog": 0.3,
    "cat": 0.3,
    "chair": 0.2,
}
CLASS_THRESHOLDS_TEXT = ",".join(f"{name}={value}" for name, value in CLASS_THRESHOLDS.items())
NMS_THRESHOLD = 0.35
MAX_DETECTIONS = 100

RUN_THRESHOLD_SWEEP = True
CLASS_THRESHOLD_CONFIGS = [
    {
        "name": "balanced",
        "default": 0.25,
        "thresholds": CLASS_THRESHOLDS,
    },
    {
        "name": "more_recall",
        "default": 0.20,
        "thresholds": {"person": 0.20, "car": 0.15, "dog": 0.20, "cat": 0.20, "chair": 0.08},
    },
    {
        "name": "clean",
        "default": 0.30,
        "thresholds": {"person": 0.30, "car": 0.25, "dog": 0.25, "cat": 0.30, "chair": 0.15},
    },
    {
        "name": "map_oriented",
        "default": 0.15,
        "thresholds": {"person": 0.15, "car": 0.15, "dog": 0.15, "cat": 0.15, "chair": 0.08},
    },
]
NMS_VALUES = [0.35, 0.45, 0.50]

# Optional hidden/test image directory. Leave as None if you only want val predictions.
TEST_IMAGE_DIR = None
FINAL_PREDICTIONS = Path("/kaggle/working/predictions.json")

## 2. Clone Code And Install Requirements

In [2]:
import os
import subprocess
import sys

if not PROJECT_DIR.exists():
    if "YOUR_USERNAME" in REPO_URL or "YOUR_REPO" in REPO_URL:
        raise ValueError("Edit REPO_URL in the settings cell before cloning.")
    clone_cmd = ["git", "clone"]
    clone_cmd += [REPO_URL, str(PROJECT_DIR)]
    subprocess.run(clone_cmd, check=True)
else:
    print(f"Project directory already exists: {PROJECT_DIR}")

os.chdir(PROJECT_DIR)
print("cwd:", Path.cwd())

requirements = PROJECT_DIR / "requirements.txt"
if requirements.exists():
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(requirements)], check=True)

import torch
print("python:", sys.version)
print("torch:", torch.__version__)
print("cuda_available:", torch.cuda.is_available())

Cloning into '/kaggle/working/object-detection'...

cwd: /kaggle/working/object-detection
python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
torch: 2.10.0+cu128
cuda_available: True

## 3. Locate Kaggle Input Dataset

In [3]:
PUBLIC_DIR = Path("/kaggle/input/datasets/duong1589/object-detection/public")
TRAIN_JSON = PUBLIC_DIR / "annotations" / "train.json"
VAL_JSON = PUBLIC_DIR / "annotations" / "val.json"
TRAIN_IMAGES = PUBLIC_DIR / "train" / "images"
VAL_IMAGES = PUBLIC_DIR / "val" / "images"
EVALUATOR = PUBLIC_DIR / "tools" / "evaluate_predictions.py"

print("PUBLIC_DIR:", PUBLIC_DIR)
print("TRAIN_JSON:", TRAIN_JSON)
print("VAL_JSON:", VAL_JSON)
print("TRAIN_IMAGES:", TRAIN_IMAGES)
print("VAL_IMAGES:", VAL_IMAGES)
print("EVALUATOR:", EVALUATOR, EVALUATOR.exists())

PUBLIC_DIR: /kaggle/input/datasets/duong1589/object-detection/public
TRAIN_JSON: /kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json
VAL_JSON: /kaggle/input/datasets/duong1589/object-detection/public/annotations/val.json
TRAIN_IMAGES: /kaggle/input/datasets/duong1589/object-detection/public/train/images
VAL_IMAGES: /kaggle/input/datasets/duong1589/object-detection/public/val/images
EVALUATOR: /kaggle/input/datasets/duong1589/object-detection/public/tools/evaluate_predictions.py True

## 4. Sanity Check Dataset And Code

In [4]:
import json

for split_name, json_path in [("train", TRAIN_JSON), ("val", VAL_JSON)]:
    data = json.loads(json_path.read_text(encoding="utf-8"))
    print(split_name, "images=", len(data["images"]), "annotations=", len(data["annotations"]))

subprocess.run([sys.executable, "-m", "py_compile", "train.py", "predict.py"], check=True)
subprocess.run([
    sys.executable, "-m", "utils.check_dataset",
    "--annotations", str(TRAIN_JSON),
    "--image_dir", str(TRAIN_IMAGES),
    "--image_size", str(IMAGE_SIZE),
    "--batch_size", "2",
    "--train",
], check=True)

train images= 7500 annotations= 10642
val images= 1500 annotations= 2021
dataset_size=7500
classes=['person', 'car', 'dog', 'cat', 'chair']
sample_image_shape=(3, 640, 640)
sample_image_id=img_000c52c6d12f.jpg
sample_boxes=(1, 4)
batch_image_shape=(2, 3, 640, 640)
batch_box_counts=[0, 0]

CompletedProcess(args=['/usr/bin/python3', '-m', 'utils.check_dataset', '--annotations', '/kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json', '--image_dir', '/kaggle/input/datasets/duong1589/object-detection/public/train/images', '--image_size', '640', '--batch_size', '2', '--train'], returncode=0)

## 5. Train

In [5]:
from IPython.display import display
import pandas as pd

train_cmd = [
    sys.executable, "train.py",
    "--train_data", str(TRAIN_JSON),
    "--val_data", str(VAL_JSON),
    "--image_dir", str(TRAIN_IMAGES),
    "--val_image_dir", str(VAL_IMAGES),
    "--checkpoint_dir", str(PROJECT_DIR / "models"),
    "--image_size", str(IMAGE_SIZE),
    "--epochs", str(EPOCHS),
    "--batch_size", str(BATCH_SIZE),
    "--num_workers", str(NUM_WORKERS),
    "--lr", str(LR),
    "--weight_decay", str(WEIGHT_DECAY),
    "--reg_max", str(REG_MAX),
    "--small_object_max_side", str(SMALL_OBJECT_MAX_SIDE),
    "--medium_object_max_side", str(MEDIUM_OBJECT_MAX_SIDE),
    "--tal_topk", str(TAL_TOPK),
    "--tal_alpha", str(TAL_ALPHA),
    "--tal_beta", str(TAL_BETA),
    "--backbone", BACKBONE_NAME,
    "--neck", NECK_NAME,
    "--conf_threshold", str(CONF_THRESHOLD),
    "--class_thresholds", CLASS_THRESHOLDS_TEXT,
    "--nms_threshold", str(NMS_THRESHOLD),
]
if DISABLE_TQDM:
    train_cmd.append("--disable_tqdm")
if USE_AMP:
    train_cmd.append("--amp")
if USE_PRETRAINED_BACKBONE:
    train_cmd.append("--pretrained_backbone")
if FREEZE_BACKBONE_STEM:
    train_cmd.append("--freeze_backbone_stem")
if OVERSAMPLE_CLASSES and OVERSAMPLE_FACTOR > 1.0:
    train_cmd += ["--oversample_classes", *OVERSAMPLE_CLASSES]
    train_cmd += ["--oversample_factor", str(OVERSAMPLE_FACTOR)]
if MAX_TRAIN_BATCHES > 0:
    train_cmd += ["--max_train_batches", str(MAX_TRAIN_BATCHES)]
if MAX_VAL_BATCHES > 0:
    train_cmd += ["--max_val_batches", str(MAX_VAL_BATCHES)]

print("Train command:")
print(" ".join(train_cmd))
subprocess.run(train_cmd, check=True)

history_files = sorted((PROJECT_DIR / "models").glob("train_history_*.csv"), key=lambda item: item.stat().st_mtime)
if history_files:
    HISTORY_CSV = history_files[-1]
    history_df = pd.read_csv(HISTORY_CSV)
    print("History CSV:", HISTORY_CSV)
    display_columns = [
        "epoch", "epoch_seconds", "train_seconds", "val_seconds", "lr",
        "train_loss", "val_loss", "val_map50", "val_micro_f1", "val_macro_f1",
        "best_map50", "best_val_loss", "best_micro_f1",
        "train_box_loss", "train_dfl_loss", "train_objectness_loss", "train_class_loss",
        "val_box_loss", "val_dfl_loss", "val_objectness_loss", "val_class_loss",
    ]
    display(history_df[[col for col in display_columns if col in history_df.columns]].tail(10))
else:
    HISTORY_CSV = None
    print("No train history CSV found.")

Train command:
/usr/bin/python3 train.py --train_data /kaggle/input/datasets/duong1589/object-detection/public/annotations/train.json --val_data /kaggle/input/datasets/duong1589/object-detection/public/annotations/val.json --image_dir /kaggle/input/datasets/duong1589/object-detection/public/train/images --val_image_dir /kaggle/input/datasets/duong1589/object-detection/public/val/images --checkpoint_dir /kaggle/working/object-detection/models --image_size 640 --epochs 30 --batch_size 16 --num_workers 2 --lr 0.0001 --weight_decay 0.0001 --reg_max 16 --small_object_max_side 96.0 --medium_object_max_side 224.0 --tal_topk 10 --tal_alpha 1.0 --tal_beta 6.0 --backbone resnet101 --conf_threshold 0.25 --class_thresholds person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 --nms_threshold 0.35 --disable_tqdm --amp --pretrained_backbone --oversample_classes chair --oversample_factor 2.0
device=cuda amp=True
Downloading: "https://download.pytorch.org/models/resnet101-cd907fc2.pth" to /root/.cache/torch/hub/checkpoints/resnet101-cd907fc2.pth

100%|██████████| 171M/171M [00:01<00:00, 167MB/s]

class_thresholds: person=0.350, car=0.250, dog=0.300, cat=0.300, chair=0.200
epoch=1/30 epoch_time=11m13s train_time=9m37s val_time=1m31s lr=6.66667e-05 train_loss=4.0359 train_dfl=2.1149 val_loss=3.3268 val_dfl=1.7627 val_map50=0.2037 val_f1=0.4010 best_map50=0.2037 best_val_loss=3.3268 best_f1=0.4010
epoch=2/30 epoch_time=11m32s train_time=9m54s val_time=1m32s lr=0.0001 train_loss=2.9516 train_dfl=1.5815 val_loss=2.7129 val_dfl=1.4425 val_map50=0.4731 val_f1=0.5912 best_map50=0.4731 best_val_loss=2.7129 best_f1=0.5912
epoch=3/30 epoch_time=11m31s train_time=9m53s val_time=1m31s lr=0.0001 train_loss=2.5325 train_dfl=1.3705 val_loss=2.5759 val_dfl=1.3675 val_map50=0.5155 val_f1=0.6503 best_map50=0.5155 best_val_loss=2.5759 best_f1=0.6503
epoch=4/30 epoch_time=11m33s train_time=9m53s val_time=1m32s lr=9.96619e-05 train_loss=2.2343 train_dfl=1.2275 val_loss=2.4587 val_dfl=1.3154 val_map50=0.5916 val_f1=0.6711 best_map50=0.5916 best_val_loss=2.4587 best_f1=0.6711
epoch=5/30 epoch_time=11m30s train_time=9m52s val_time=1m31s lr=9.86522e-05 train_loss=2.0526 train_dfl=1.1376 val_loss=2.3511 val_dfl=1.2744 val_map50=0.6156 val_f1=0.6970 best_map50=0.6156 best_val_loss=2.3511 best_f1=0.6970
epoch=6/30 epoch_time=11m24s train_time=9m45s val_time=1m32s lr=9.69846e-05 train_loss=1.9044 train_dfl=1.0675 val_loss=2.3841 val_dfl=1.2895 val_map50=0.6208 val_f1=0.7078 best_map50=0.6208 best_val_loss=2.3511 best_f1=0.7078
epoch=7/30 epoch_time=11m29s train_time=9m53s val_time=1m32s lr=9.46816e-05 train_loss=1.7789 train_dfl=1.0132 val_loss=2.3253 val_dfl=1.2655 val_map50=0.6302 val_f1=0.7077 best_map50=0.6302 best_val_loss=2.3253 best_f1=0.7078
epoch=8/30 epoch_time=11m28s train_time=9m53s val_time=1m32s lr=9.17744e-05 train_loss=1.6740 train_dfl=0.9725 val_loss=2.2840 val_dfl=1.2592 val_map50=0.5990 val_f1=0.7105 best_map50=0.6302 best_val_loss=2.2840 best_f1=0.7105
epoch=9/30 epoch_time=11m28s train_time=9m51s val_time=1m32s lr=8.83022e-05 train_loss=1.5658 train_dfl=0.9177 val_loss=2.2824 val_dfl=1.2597 val_map50=0.6591 val_f1=0.7207 best_map50=0.6591 best_val_loss=2.2824 best_f1=0.7207
epoch=10/30 epoch_time=11m34s train_time=9m59s val_time=1m34s lr=8.43121e-05 train_loss=1.5186 train_dfl=0.8925 val_loss=2.3126 val_dfl=1.2715 val_map50=0.6082 val_f1=0.7167 best_map50=0.6591 best_val_loss=2.2824 best_f1=0.7207
epoch=11/30 epoch_time=11m37s train_time=9m58s val_time=1m34s lr=7.98579e-05 train_loss=1.4327 train_dfl=0.8597 val_loss=2.2576 val_dfl=1.2547 val_map50=0.6479 val_f1=0.7358 best_map50=0.6591 best_val_loss=2.2576 best_f1=0.7358
epoch=12/30 epoch_time=11m31s train_time=9m55s val_time=1m34s lr=7.5e-05 train_loss=1.3604 train_dfl=0.8247 val_loss=2.2586 val_dfl=1.2578 val_map50=0.6450 val_f1=0.7194 best_map50=0.6591 best_val_loss=2.2576 best_f1=0.7358
epoch=13/30 epoch_time=11m38s train_time=9m56s val_time=1m34s lr=6.9804e-05 train_loss=1.3075 train_dfl=0.8006 val_loss=2.2426 val_dfl=1.2538 val_map50=0.6608 val_f1=0.7503 best_map50=0.6608 best_val_loss=2.2426 best_f1=0.7503
epoch=14/30 epoch_time=11m35s train_time=9m58s val_time=1m34s lr=6.43402e-05 train_loss=1.2667 train_dfl=0.7828 val_loss=2.2402 val_dfl=1.2586 val_map50=0.6537 val_f1=0.7482 best_map50=0.6608 best_val_loss=2.2402 best_f1=0.7503
epoch=15/30 epoch_time=11m32s train_time=9m52s val_time=1m34s lr=5.86824e-05 train_loss=1.2126 train_dfl=0.7608 val_loss=2.2153 val_dfl=1.2449 val_map50=0.6668 val_f1=0.7471 best_map50=0.6668 best_val_loss=2.2153 best_f1=0.7503
epoch=16/30 epoch_time=11m24s train_time=9m49s val_time=1m34s lr=5.29072e-05 train_loss=1.1786 train_dfl=0.7457 val_loss=2.2419 val_dfl=1.2623 val_map50=0.6428 val_f1=0.7431 best_map50=0.6668 best_val_loss=2.2153 best_f1=0.7503
epoch=17/30 epoch_time=11m28s train_time=9m56s val_time=1m32s lr=4.70928e-05 train_loss=1.1520 train_dfl=0.7332 val_loss=2.2288 val_dfl=1.2592 val_map50=0.6622 val_f1=0.7407 best_map50=0.6668 best_val_loss=2.2153 best_f1=0.7503
epoch=18/30 epoch_time=11m25s train_time=9m52s val_time=1m32s lr=4.13176e-05 train_loss=1.1055 train_dfl=0.7162 val_loss=2.2279 val_dfl=1.2543 val_map50=0.6494 val_f1=0.7441 best_map50=0.6668 best_val_loss=2.2153 best_f1=0.7503
epoch=19/30 epoch_time=11m25s train_time=9m51s val_time=1m32s lr=3.56598e-05 train_loss=1.0759 train_dfl=0.7020 val_loss=2.2010 val_dfl=1.2531 val_map50=0.6417 val_f1=0.7501 best_map50=0.6668 best_val_loss=2.2010 best_f1=0.7503
epoch=20/30 epoch_time=11m29s train_time=9m53s val_time=1m32s lr=3.0196e-05 train_loss=1.0434 train_dfl=0.6875 val_loss=2.2070 val_dfl=1.2558 val_map50=0.6739 val_f1=0.7546 best_map50=0.6739 best_val_loss=2.2010 best_f1=0.7546
epoch=21/30 epoch_time=11m26s train_time=9m51s val_time=1m31s lr=2.5e-05 train_loss=1.0293 train_dfl=0.6819 val_loss=2.1918 val_dfl=1.2416 val_map50=0.6545 val_f1=0.7549 best_map50=0.6739 best_val_loss=2.1918 best_f1=0.7549
epoch=22/30 epoch_time=11m25s train_time=9m51s val_time=1m32s lr=2.01421e-05 train_loss=0.9827 train_dfl=0.6639 val_loss=2.1963 val_dfl=1.2485 val_map50=0.6614 val_f1=0.7557 best_map50=0.6739 best_val_loss=2.1918 best_f1=0.7557
epoch=23/30 epoch_time=11m22s train_time=9m47s val_time=1m32s lr=1.56879e-05 train_loss=0.9705 train_dfl=0.6596 val_loss=2.1829 val_dfl=1.2405 val_map50=0.6650 val_f1=0.7627 best_map50=0.6739 best_val_loss=2.1829 best_f1=0.7627
epoch=24/30 epoch_time=11m27s train_time=9m52s val_time=1m32s lr=1.16978e-05 train_loss=0.9513 train_dfl=0.6496 val_loss=2.1790 val_dfl=1.2412 val_map50=0.6726 val_f1=0.7705 best_map50=0.6739 best_val_loss=2.1790 best_f1=0.7705
epoch=25/30 epoch_time=11m26s train_time=9m52s val_time=1m31s lr=8.22561e-06 train_loss=0.9290 train_dfl=0.6421 val_loss=2.1753 val_dfl=1.2316 val_map50=0.6647 val_f1=0.7685 best_map50=0.6739 best_val_loss=2.1753 best_f1=0.7705
epoch=26/30 epoch_time=11m17s train_time=9m44s val_time=1m31s lr=5.31837e-06 train_loss=0.9215 train_dfl=0.6403 val_loss=2.1730 val_dfl=1.2356 val_map50=0.6664 val_f1=0.7668 best_map50=0.6739 best_val_loss=2.1730 best_f1=0.7705
epoch=27/30 epoch_time=11m26s train_time=9m49s val_time=1m31s lr=3.01537e-06 train_loss=0.9097 train_dfl=0.6354 val_loss=2.1787 val_dfl=1.2436 val_map50=0.6811 val_f1=0.7724 best_map50=0.6811 best_val_loss=2.1730 best_f1=0.7724
epoch=28/30 epoch_time=11m23s train_time=9m50s val_time=1m31s lr=1.34776e-06 train_loss=0.9022 train_dfl=0.6333 val_loss=2.1753 val_dfl=1.2366 val_map50=0.6637 val_f1=0.7683 best_map50=0.6811 best_val_loss=2.1730 best_f1=0.7724
epoch=29/30 epoch_time=11m24s train_time=9m52s val_time=1m31s lr=3.38082e-07 train_loss=0.9014 train_dfl=0.6322 val_loss=2.1752 val_dfl=1.2365 val_map50=0.6644 val_f1=0.7707 best_map50=0.6811 best_val_loss=2.1730 best_f1=0.7724
epoch=30/30 epoch_time=11m24s train_time=9m50s val_time=1m32s lr=0 train_loss=0.8954 train_dfl=0.6323 val_loss=2.1675 val_dfl=1.2323 val_map50=0.6715 val_f1=0.7708 best_map50=0.6811 best_val_loss=2.1675 best_f1=0.7724
best_map50_checkpoint=/kaggle/working/object-detection/models/best_map50.pth
best_val_loss_checkpoint=/kaggle/working/object-detection/models/best_val_loss.pth
best_f1_checkpoint=/kaggle/working/object-detection/models/best_f1.pth
best_checkpoint=/kaggle/working/object-detection/models/best.pth
history=/kaggle/working/object-detection/models/train_history_20260611_064337.csv
History CSV: /kaggle/working/object-detection/models/train_history_20260611_064337.csv

,epoch,epoch_seconds,train_seconds,val_seconds,lr,train_loss,val_loss,val_map50,val_micro_f1,val_macro_f1,...,best_val_loss,best_micro_f1,train_box_loss,train_dfl_loss,train_objectness_loss,train_class_loss,val_box_loss,val_dfl_loss,val_objectness_loss,val_class_loss
20,21,686.10,591.45,91.01,2.500000e-05,1.029335,2.191788,0.654489,0.754870,0.746024,...,2.191788,0.754870,0.063821,0.681903,0.025879,0.004897,0.174873,1.241614,0.054477,0.042666
21,22,685.15,591.18,91.52,2.014207e-05,0.982742,2.196252,0.661357,0.755721,0.746931,...,2.191788,0.755721,0.058678,0.663940,0.024233,0.002361,0.175042,1.248461,0.054028,0.037102
22,23,682.13,586.87,91.55,1.568792e-05,0.970548,2.182941,0.664985,0.762726,0.751065,...,2.182941,0.762726,0.057312,0.659601,0.023121,0.002531,0.173989,1.240464,0.051426,0.042210
23,24,687.29,591.86,91.63,1.169778e-05,0.951334,2.179027,0.672613,0.770474,0.760320,...,2.179027,0.770474,0.055647,0.649583,0.022402,0.002234,0.173377,1.241190,0.050274,0.041355
24,25,685.72,591.92,91.30,8.225609e-06,0.929024,2.175312,0.664701,0.768519,0.756758,...,2.175312,0.770474,0.052941,0.642057,0.021365,0.001791,0.174150,1.231592,0.051893,0.042150
25,26,677.31,583.71,91.18,5.318368e-06,0.921466,2.172992,0.666370,0.766848,0.758290,...,2.172992,0.770474,0.051793,0.640271,0.021101,0.002261,0.173825,1.235616,0.051010,0.034485
26,27,685.71,589.17,91.48,3.015369e-06,0.909746,2.178662,0.681145,0.772373,0.765710,...,2.172992,0.772373,0.050626,0.635357,0.020317,0.001883,0.173274,1.243552,0.050127,0.037221
27,28,682.81,590.26,91.33,1.347756e-06,0.902190,2.175259,0.663736,0.768346,0.758136,...,2.172992,0.772373,0.049550,0.633278,0.020385,0.001555,0.173656,1.236563,0.052359,0.036115
28,29,684.38,591.83,91.32,3.380821e-07,0.901411,2.175194,0.664391,0.770748,0.761004,...,2.172992,0.772373,0.049600,0.632165,0.020192,0.002109,0.173612,1.236485,0.052392,0.036513
29,30,683.91,589.67,91.73,0.000000e+00,0.895381,2.167502,0.671550,0.770777,0.761150,...,2.167502,0.772373,0.048540,0.632305,0.019617,0.001521,0.173169,1.232251,0.051677,0.035454

## 6. Predict On Validation And Evaluate

In [6]:
VAL_PREDICTIONS = PROJECT_DIR / "val_predictions.json"
predict_val_cmd = [
    sys.executable, "predict.py",
    "--image_dir", str(VAL_IMAGES),
    "--output", str(VAL_PREDICTIONS),
    "--checkpoint", str(PROJECT_DIR / "models" / "best.pth"),
    "--batch_size", str(BATCH_SIZE),
    "--conf_threshold", str(CONF_THRESHOLD),
    "--class_thresholds", CLASS_THRESHOLDS_TEXT,
    "--nms_threshold", str(NMS_THRESHOLD),
    "--max_detections", str(MAX_DETECTIONS),
]
print("Predict validation command:")
print(" ".join(predict_val_cmd))
subprocess.run(predict_val_cmd, check=True)

val_predictions_data = json.loads(VAL_PREDICTIONS.read_text(encoding="utf-8"))
num_pred_boxes = sum(len(item["boxes"]) for item in val_predictions_data)
print(f"Validation predictions: images={len(val_predictions_data)} boxes={num_pred_boxes}")
print("Prediction preview:")
print(json.dumps(val_predictions_data[:3], ensure_ascii=False, indent=2))

if EVALUATOR.exists():
    VAL_SCORE = PROJECT_DIR / "val_score.json"
    subprocess.run([
        sys.executable, str(EVALUATOR),
        "--ground_truth", str(VAL_JSON),
        "--predictions", str(VAL_PREDICTIONS),
        "--output", str(VAL_SCORE),
    ], check=True)
    score = json.loads(VAL_SCORE.read_text(encoding="utf-8"))
    print("Validation score:")
    print(json.dumps(score, ensure_ascii=False, indent=2))
    if "per_class" in score:
        per_class_df = pd.DataFrame.from_dict(score["per_class"], orient="index")
        display(per_class_df)
else:
    VAL_SCORE = None
    print("Evaluator not found, skipped local validation scoring.")

Predict validation command:
/usr/bin/python3 predict.py --image_dir /kaggle/input/datasets/duong1589/object-detection/public/val/images --output /kaggle/working/object-detection/val_predictions.json --checkpoint /kaggle/working/object-detection/models/best.pth --batch_size 16 --conf_threshold 0.25 --class_thresholds person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 --nms_threshold 0.35 --max_detections 100
wrote 1500 predictions to /kaggle/working/object-detection/val_predictions.json
Validation predictions: images=1500 boxes=1700
Prediction preview:
[
  {
    "image_id": "img_00090df9158f.jpg",
    "boxes": [
      {
        "class": "dog",
        "confidence": 0.547608,
        "bbox": [
          119.04,
          68.78,
          500.0,
          374.84
        ]
      }
    ]
  },
  {
    "image_id": "img_003c3ddc6a82.jpg",
    "boxes": [
      {
        "class": "person",
        "confidence": 0.352422,
        "bbox": [
          6.37,
          102.09,
          422.92,
          368.11
        ]
      }
    ]
  },
  {
    "image_id": "img_01073356e41c.jpg",
    "boxes": [
      {
        "class": "chair",
        "confidence": 0.629346,
        "bbox": [
          388.83,
          20.82,
          465.84,
          133.6
        ]
      }
    ]
  }
]
{
  "mAP@0.5": 0.681145,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1700,
  "micro_precision": 0.845294,
  "micro_recall": 0.711034,
  "per_class": {
    "person": {
      "ap": 0.706271,
      "num_ground_truth": 1074,
      "num_predictions": 868,
      "true_positives": 779,
      "false_positives": 89,
      "recall": 0.725326,
      "precision": 0.897465
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.754498,
      "num_ground_truth": 206,
      "num_predictions": 176,
      "true_positives": 159,
      "false_positives": 17,
      "recall": 0.771845,
      "precision": 0.903409
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.455111,
      "num_ground_truth": 282,
      "num_predictions": 241,
      "true_positives": 149,
      "false_positives": 92,
      "recall": 0.528369,
      "precision": 0.618257
    }
  }
}
Validation score:
{
  "mAP@0.5": 0.681145,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1700,
  "micro_precision": 0.845294,
  "micro_recall": 0.711034,
  "per_class": {
    "person": {
      "ap": 0.706271,
      "num_ground_truth": 1074,
      "num_predictions": 868,
      "true_positives": 779,
      "false_positives": 89,
      "recall": 0.725326,
      "precision": 0.897465
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.754498,
      "num_ground_truth": 206,
      "num_predictions": 176,
      "true_positives": 159,
      "false_positives": 17,
      "recall": 0.771845,
      "precision": 0.903409
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.455111,
      "num_ground_truth": 282,
      "num_predictions": 241,
      "true_positives": 149,
      "false_positives": 92,
      "recall": 0.528369,
      "precision": 0.618257
    }
  }
}

,ap,num_ground_truth,num_predictions,true_positives,false_positives,recall,precision
person,0.706271,1074,868,779,89,0.725326,0.897465
car,0.691985,283,254,205,49,0.724382,0.807087
dog,0.754498,206,176,159,17,0.771845,0.903409
cat,0.797859,176,161,145,16,0.823864,0.900621
chair,0.455111,282,241,149,92,0.528369,0.618257

## 7. Threshold Sweep On Validation

In [7]:
import json
import pandas as pd

BEST_CHECKPOINT = PROJECT_DIR / "models" / "best.pth"

def thresholds_to_text(thresholds):
    return ",".join(f"{name}={value}" for name, value in thresholds.items())

if RUN_THRESHOLD_SWEEP:
    if not (VAL_JSON.exists() and EVALUATOR.exists()):
        raise FileNotFoundError("Need VAL_JSON and EVALUATOR for threshold sweep.")
    rows = []
    sweep_dir = PROJECT_DIR / "threshold_sweep"
    sweep_dir.mkdir(parents=True, exist_ok=True)
    for config in CLASS_THRESHOLD_CONFIGS:
        config_name = config["name"]
        default_conf = config["default"]
        thresholds = config["thresholds"]
        thresholds_text = thresholds_to_text(thresholds)
        safe_thresholds = thresholds_text.replace(",", "_").replace("=", "-")
        for nms in NMS_VALUES:
            sweep_pred = sweep_dir / f"predictions_{config_name}_nms{nms:.2f}_{safe_thresholds}.json"
            sweep_score = sweep_dir / f"score_{config_name}_nms{nms:.2f}_{safe_thresholds}.json"
            print(f"Running config={config_name} default={default_conf:.2f} thresholds={thresholds_text} nms={nms:.2f}")
            !{sys.executable} predict.py --image_dir "{VAL_IMAGES}" --output "{sweep_pred}" --checkpoint "{BEST_CHECKPOINT}" --batch_size {BATCH_SIZE} --conf_threshold {default_conf} --class_thresholds "{thresholds_text}" --nms_threshold {nms} --max_detections {MAX_DETECTIONS}
            !{sys.executable} "{EVALUATOR}" --ground_truth "{VAL_JSON}" --predictions "{sweep_pred}" --output "{sweep_score}"
            score = json.loads(sweep_score.read_text(encoding="utf-8"))
            per_class = score.get("per_class", {})
            chair = per_class.get("chair", {})
            rows.append({
                "config": config_name,
                "thresholds": thresholds_text,
                "default_conf": default_conf,
                "nms": nms,
                "map50": score.get("mAP@0.5", 0.0),
                "performance_points": score.get("performance_points", 0),
                "precision": score.get("micro_precision", 0.0),
                "recall": score.get("micro_recall", 0.0),
                "num_predictions": score.get("num_predictions", 0),
                "chair_ap": chair.get("ap", 0.0),
                "chair_precision": chair.get("precision", 0.0),
                "chair_recall": chair.get("recall", 0.0),
            })
    sweep_df = pd.DataFrame(rows).sort_values(["map50", "precision"], ascending=[False, False])
    sweep_csv = sweep_dir / "threshold_sweep_results.csv"
    sweep_df.to_csv(sweep_csv, index=False)
    print("Threshold sweep results:", sweep_csv)
    display(sweep_df)
else:
    print("Threshold sweep disabled. Set RUN_THRESHOLD_SWEEP = True to run it.")

Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.35_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.681145,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1700,
  "micro_precision": 0.845294,
  "micro_recall": 0.711034,
  "per_class": {
    "person": {
      "ap": 0.706271,
      "num_ground_truth": 1074,
      "num_predictions": 868,
      "true_positives": 779,
      "false_positives": 89,
      "recall": 0.725326,
      "precision": 0.897465
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.754498,
      "num_ground_truth": 206,
      "num_predictions": 176,
      "true_positives": 159,
      "false_positives": 17,
      "recall": 0.771845,
      "precision": 0.903409
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.455111,
      "num_ground_truth": 282,
      "num_predictions": 241,
      "true_positives": 149,
      "false_positives": 92,
      "recall": 0.528369,
      "precision": 0.618257
    }
  }
}
Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.45_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.682866,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1711,
  "micro_precision": 0.843366,
  "micro_recall": 0.714003,
  "per_class": {
    "person": {
      "ap": 0.709802,
      "num_ground_truth": 1074,
      "num_predictions": 873,
      "true_positives": 783,
      "false_positives": 90,
      "recall": 0.72905,
      "precision": 0.896907
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.754498,
      "num_ground_truth": 206,
      "num_predictions": 177,
      "true_positives": 159,
      "false_positives": 18,
      "recall": 0.771845,
      "precision": 0.898305
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.460185,
      "num_ground_truth": 282,
      "num_predictions": 246,
      "true_positives": 151,
      "false_positives": 95,
      "recall": 0.535461,
      "precision": 0.613821
    }
  }
}
Running config=balanced default=0.25 thresholds=person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_balanced_nms0.50_person-0.35_car-0.25_dog-0.3_cat-0.3_chair-0.2.json
{
  "mAP@0.5": 0.684313,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1720,
  "micro_precision": 0.841279,
  "micro_recall": 0.715982,
  "per_class": {
    "person": {
      "ap": 0.711439,
      "num_ground_truth": 1074,
      "num_predictions": 880,
      "true_positives": 785,
      "false_positives": 95,
      "recall": 0.730912,
      "precision": 0.892045
    },
    "car": {
      "ap": 0.695326,
      "num_ground_truth": 283,
      "num_predictions": 255,
      "true_positives": 206,
      "false_positives": 49,
      "recall": 0.727915,
      "precision": 0.807843
    },
    "dog": {
      "ap": 0.754498,
      "num_ground_truth": 206,
      "num_predictions": 177,
      "true_positives": 159,
      "false_positives": 18,
      "recall": 0.771845,
      "precision": 0.898305
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.462444,
      "num_ground_truth": 282,
      "num_predictions": 247,
      "true_positives": 152,
      "false_positives": 95,
      "recall": 0.539007,
      "precision": 0.615385
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.35_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.715,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2248,
  "micro_precision": 0.69395,
  "micro_recall": 0.771895,
  "per_class": {
    "person": {
      "ap": 0.765269,
      "num_ground_truth": 1074,
      "num_predictions": 1029,
      "true_positives": 852,
      "false_positives": 177,
      "recall": 0.793296,
      "precision": 0.827988
    },
    "car": {
      "ap": 0.720984,
      "num_ground_truth": 283,
      "num_predictions": 312,
      "true_positives": 216,
      "false_positives": 96,
      "recall": 0.763251,
      "precision": 0.692308
    },
    "dog": {
      "ap": 0.767104,
      "num_ground_truth": 206,
      "num_predictions": 198,
      "true_positives": 162,
      "false_positives": 36,
      "recall": 0.786408,
      "precision": 0.818182
    },
    "cat": {
      "ap": 0.807982,
      "num_ground_truth": 176,
      "num_predictions": 170,
      "true_positives": 147,
      "false_positives": 23,
      "recall": 0.835227,
      "precision": 0.864706
    },
    "chair": {
      "ap": 0.513659,
      "num_ground_truth": 282,
      "num_predictions": 539,
      "true_positives": 183,
      "false_positives": 356,
      "recall": 0.648936,
      "precision": 0.339518
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.45_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.717671,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2280,
  "micro_precision": 0.688596,
  "micro_recall": 0.776843,
  "per_class": {
    "person": {
      "ap": 0.770434,
      "num_ground_truth": 1074,
      "num_predictions": 1040,
      "true_positives": 858,
      "false_positives": 182,
      "recall": 0.798883,
      "precision": 0.825
    },
    "car": {
      "ap": 0.720932,
      "num_ground_truth": 283,
      "num_predictions": 313,
      "true_positives": 216,
      "false_positives": 97,
      "recall": 0.763251,
      "precision": 0.690096
    },
    "dog": {
      "ap": 0.767036,
      "num_ground_truth": 206,
      "num_predictions": 199,
      "true_positives": 162,
      "false_positives": 37,
      "recall": 0.786408,
      "precision": 0.81407
    },
    "cat": {
      "ap": 0.807982,
      "num_ground_truth": 176,
      "num_predictions": 170,
      "true_positives": 147,
      "false_positives": 23,
      "recall": 0.835227,
      "precision": 0.864706
    },
    "chair": {
      "ap": 0.521968,
      "num_ground_truth": 282,
      "num_predictions": 558,
      "true_positives": 187,
      "false_positives": 371,
      "recall": 0.663121,
      "precision": 0.335125
    }
  }
}
Running config=more_recall default=0.20 thresholds=person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_more_recall_nms0.50_person-0.2_car-0.15_dog-0.2_cat-0.2_chair-0.08.json
{
  "mAP@0.5": 0.719592,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2296,
  "micro_precision": 0.685976,
  "micro_recall": 0.779317,
  "per_class": {
    "person": {
      "ap": 0.772524,
      "num_ground_truth": 1074,
      "num_predictions": 1049,
      "true_positives": 861,
      "false_positives": 188,
      "recall": 0.801676,
      "precision": 0.820782
    },
    "car": {
      "ap": 0.724283,
      "num_ground_truth": 283,
      "num_predictions": 315,
      "true_positives": 217,
      "false_positives": 98,
      "recall": 0.766784,
      "precision": 0.688889
    },
    "dog": {
      "ap": 0.770997,
      "num_ground_truth": 206,
      "num_predictions": 200,
      "true_positives": 163,
      "false_positives": 37,
      "recall": 0.791262,
      "precision": 0.815
    },
    "cat": {
      "ap": 0.807982,
      "num_ground_truth": 176,
      "num_predictions": 171,
      "true_positives": 147,
      "false_positives": 24,
      "recall": 0.835227,
      "precision": 0.859649
    },
    "chair": {
      "ap": 0.522172,
      "num_ground_truth": 282,
      "num_predictions": 561,
      "true_positives": 187,
      "false_positives": 374,
      "recall": 0.663121,
      "precision": 0.333333
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.35_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.692169,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1834,
  "micro_precision": 0.805344,
  "micro_recall": 0.730826,
  "per_class": {
    "person": {
      "ap": 0.727023,
      "num_ground_truth": 1074,
      "num_predictions": 912,
      "true_positives": 804,
      "false_positives": 108,
      "recall": 0.748603,
      "precision": 0.881579
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.763132,
      "num_ground_truth": 206,
      "num_predictions": 188,
      "true_positives": 161,
      "false_positives": 27,
      "recall": 0.781553,
      "precision": 0.856383
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.480846,
      "num_ground_truth": 282,
      "num_predictions": 319,
      "true_positives": 162,
      "false_positives": 157,
      "recall": 0.574468,
      "precision": 0.507837
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.45_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.694908,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1853,
  "micro_precision": 0.802482,
  "micro_recall": 0.735774,
  "per_class": {
    "person": {
      "ap": 0.732209,
      "num_ground_truth": 1074,
      "num_predictions": 919,
      "true_positives": 810,
      "false_positives": 109,
      "recall": 0.75419,
      "precision": 0.881393
    },
    "car": {
      "ap": 0.691985,
      "num_ground_truth": 283,
      "num_predictions": 254,
      "true_positives": 205,
      "false_positives": 49,
      "recall": 0.724382,
      "precision": 0.807087
    },
    "dog": {
      "ap": 0.763084,
      "num_ground_truth": 206,
      "num_predictions": 189,
      "true_positives": 161,
      "false_positives": 28,
      "recall": 0.781553,
      "precision": 0.851852
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.489404,
      "num_ground_truth": 282,
      "num_predictions": 330,
      "true_positives": 166,
      "false_positives": 164,
      "recall": 0.588652,
      "precision": 0.50303
    }
  }
}
Running config=clean default=0.30 thresholds=person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_clean_nms0.50_person-0.3_car-0.25_dog-0.25_cat-0.3_chair-0.15.json
{
  "mAP@0.5": 0.696105,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 1863,
  "micro_precision": 0.800322,
  "micro_recall": 0.737754,
  "per_class": {
    "person": {
      "ap": 0.734548,
      "num_ground_truth": 1074,
      "num_predictions": 927,
      "true_positives": 813,
      "false_positives": 114,
      "recall": 0.756983,
      "precision": 0.877023
    },
    "car": {
      "ap": 0.695326,
      "num_ground_truth": 283,
      "num_predictions": 255,
      "true_positives": 206,
      "false_positives": 49,
      "recall": 0.727915,
      "precision": 0.807843
    },
    "dog": {
      "ap": 0.763084,
      "num_ground_truth": 206,
      "num_predictions": 189,
      "true_positives": 161,
      "false_positives": 28,
      "recall": 0.781553,
      "precision": 0.851852
    },
    "cat": {
      "ap": 0.797859,
      "num_ground_truth": 176,
      "num_predictions": 161,
      "true_positives": 145,
      "false_positives": 16,
      "recall": 0.823864,
      "precision": 0.900621
    },
    "chair": {
      "ap": 0.48971,
      "num_ground_truth": 282,
      "num_predictions": 331,
      "true_positives": 166,
      "false_positives": 165,
      "recall": 0.588652,
      "precision": 0.501511
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.35
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.35_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.72144,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2371,
  "micro_precision": 0.668073,
  "micro_recall": 0.78377,
  "per_class": {
    "person": {
      "ap": 0.780268,
      "num_ground_truth": 1074,
      "num_predictions": 1129,
      "true_positives": 872,
      "false_positives": 257,
      "recall": 0.811918,
      "precision": 0.772365
    },
    "car": {
      "ap": 0.720984,
      "num_ground_truth": 283,
      "num_predictions": 312,
      "true_positives": 216,
      "false_positives": 96,
      "recall": 0.763251,
      "precision": 0.692308
    },
    "dog": {
      "ap": 0.774611,
      "num_ground_truth": 206,
      "num_predictions": 216,
      "true_positives": 164,
      "false_positives": 52,
      "recall": 0.796117,
      "precision": 0.759259
    },
    "cat": {
      "ap": 0.817681,
      "num_ground_truth": 176,
      "num_predictions": 175,
      "true_positives": 149,
      "false_positives": 26,
      "recall": 0.846591,
      "precision": 0.851429
    },
    "chair": {
      "ap": 0.513659,
      "num_ground_truth": 282,
      "num_predictions": 539,
      "true_positives": 183,
      "false_positives": 356,
      "recall": 0.648936,
      "precision": 0.339518
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.45
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.45_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.724383,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2411,
  "micro_precision": 0.661966,
  "micro_recall": 0.789708,
  "per_class": {
    "person": {
      "ap": 0.786855,
      "num_ground_truth": 1074,
      "num_predictions": 1147,
      "true_positives": 880,
      "false_positives": 267,
      "recall": 0.819367,
      "precision": 0.767219
    },
    "car": {
      "ap": 0.720932,
      "num_ground_truth": 283,
      "num_predictions": 313,
      "true_positives": 216,
      "false_positives": 97,
      "recall": 0.763251,
      "precision": 0.690096
    },
    "dog": {
      "ap": 0.774508,
      "num_ground_truth": 206,
      "num_predictions": 217,
      "true_positives": 164,
      "false_positives": 53,
      "recall": 0.796117,
      "precision": 0.75576
    },
    "cat": {
      "ap": 0.817653,
      "num_ground_truth": 176,
      "num_predictions": 176,
      "true_positives": 149,
      "false_positives": 27,
      "recall": 0.846591,
      "precision": 0.846591
    },
    "chair": {
      "ap": 0.521968,
      "num_ground_truth": 282,
      "num_predictions": 558,
      "true_positives": 187,
      "false_positives": 371,
      "recall": 0.663121,
      "precision": 0.335125
    }
  }
}
Running config=map_oriented default=0.15 thresholds=person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08 nms=0.50
wrote 1500 predictions to /kaggle/working/object-detection/threshold_sweep/predictions_map_oriented_nms0.50_person-0.15_car-0.15_dog-0.15_cat-0.15_chair-0.08.json
{
  "mAP@0.5": 0.726571,
  "performance_points": 20,
  "iou_threshold": 0.5,
  "num_ground_truth_boxes": 2021,
  "num_predictions": 2434,
  "micro_precision": 0.658587,
  "micro_recall": 0.793172,
  "per_class": {
    "person": {
      "ap": 0.790359,
      "num_ground_truth": 1074,
      "num_predictions": 1162,
      "true_positives": 885,
      "false_positives": 277,
      "recall": 0.824022,
      "precision": 0.761618
    },
    "car": {
      "ap": 0.724283,
      "num_ground_truth": 283,
      "num_predictions": 315,
      "true_positives": 217,
      "false_positives": 98,
      "recall": 0.766784,
      "precision": 0.688889
    },
    "dog": {
      "ap": 0.778444,
      "num_ground_truth": 206,
      "num_predictions": 219,
      "true_positives": 165,
      "false_positives": 54,
      "recall": 0.800971,
      "precision": 0.753425
    },
    "cat": {
      "ap": 0.817598,
      "num_ground_truth": 176,
      "num_predictions": 177,
      "true_positives": 149,
      "false_positives": 28,
      "recall": 0.846591,
      "precision": 0.841808
    },
    "chair": {
      "ap": 0.522172,
      "num_ground_truth": 282,
      "num_predictions": 561,
      "true_positives": 187,
      "false_positives": 374,
      "recall": 0.663121,
      "precision": 0.333333
    }
  }
}
Threshold sweep results: /kaggle/working/object-detection/threshold_sweep/threshold_sweep_results.csv

,config,thresholds,default_conf,nms,map50,performance_points,precision,recall,num_predictions,chair_ap,chair_precision,chair_recall
11,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.50,0.726571,20,0.658587,0.793172,2434,0.522172,0.333333,0.663121
10,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.45,0.724383,20,0.661966,0.789708,2411,0.521968,0.335125,0.663121
9,map_oriented,"person=0.15,car=0.15,dog=0.15,cat=0.15,chair=0.08",0.15,0.35,0.721440,20,0.668073,0.783770,2371,0.513659,0.339518,0.648936
5,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.50,0.719592,20,0.685976,0.779317,2296,0.522172,0.333333,0.663121
4,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.45,0.717671,20,0.688596,0.776843,2280,0.521968,0.335125,0.663121
3,more_recall,"person=0.2,car=0.15,dog=0.2,cat=0.2,chair=0.08",0.20,0.35,0.715000,20,0.693950,0.771895,2248,0.513659,0.339518,0.648936
8,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.50,0.696105,20,0.800322,0.737754,1863,0.489710,0.501511,0.588652
7,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.45,0.694908,20,0.802482,0.735774,1853,0.489404,0.503030,0.588652
6,clean,"person=0.3,car=0.25,dog=0.25,cat=0.3,chair=0.15",0.30,0.35,0.692169,20,0.805344,0.730826,1834,0.480846,0.507837,0.574468
2,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.50,0.684313,20,0.841279,0.715982,1720,0.462444,0.615385,0.539007
1,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.45,0.682866,20,0.843366,0.714003,1711,0.460185,0.613821,0.535461
0,balanced,"person=0.35,car=0.25,dog=0.3,cat=0.3,chair=0.2",0.25,0.35,0.681145,20,0.845294,0.711034,1700,0.455111,0.618257,0.528369

## 8. Predict On Hidden/Test Images If Available

In [8]:
if TEST_IMAGE_DIR is None:
    print("TEST_IMAGE_DIR is None. Skipped final prediction.")
else:
    test_dir = Path(TEST_IMAGE_DIR)
    final_cmd = [
        sys.executable, "predict.py",
        "--image_dir", str(test_dir),
        "--output", str(FINAL_PREDICTIONS),
        "--checkpoint", str(PROJECT_DIR / "models" / "best.pth"),
        "--batch_size", str(BATCH_SIZE),
        "--conf_threshold", str(CONF_THRESHOLD),
        "--class_thresholds", CLASS_THRESHOLDS_TEXT,
        "--nms_threshold", str(NMS_THRESHOLD),
    ]
    print("Final predict command:")
    print(" ".join(final_cmd))
    subprocess.run(final_cmd, check=True)
    final_data = json.loads(FINAL_PREDICTIONS.read_text(encoding="utf-8"))
    print(f"Final predictions: images={len(final_data)} boxes={sum(len(item['boxes']) for item in final_data)}")
    print("Final prediction preview:")
    print(json.dumps(final_data[:3], ensure_ascii=False, indent=2))
    print("Final predictions path:", FINAL_PREDICTIONS)

TEST_IMAGE_DIR is None. Skipped final prediction.

## 9. Collect Artifacts

In [9]:
import shutil

ARTIFACT_DIR = Path("/kaggle/working/artifacts")
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

files_to_copy = [
    PROJECT_DIR / "models" / "best_map50.pth",
    PROJECT_DIR / "models" / "best_val_loss.pth",
    PROJECT_DIR / "models" / "best_f1.pth",
    PROJECT_DIR / "models" / "best.pth",
    PROJECT_DIR / "models" / "last.pth",
    VAL_PREDICTIONS,
    PROJECT_DIR / "val_score.json",
]
files_to_copy += sorted((PROJECT_DIR / "models").glob("train_history_*.csv"))
sweep_results = PROJECT_DIR / "threshold_sweep" / "threshold_sweep_results.csv"
if sweep_results.exists():
    files_to_copy.append(sweep_results)
if FINAL_PREDICTIONS.exists():
    files_to_copy.append(FINAL_PREDICTIONS)

copied = []
for src in files_to_copy:
    if src.exists():
        dst = ARTIFACT_DIR / src.name
        shutil.copy2(src, dst)
        copied.append(dst)

zip_path = shutil.make_archive("/kaggle/working/object_detection_artifacts", "zip", ARTIFACT_DIR)
print("Artifacts directory:", ARTIFACT_DIR)
print("Artifacts zip:", zip_path)
print("Files:")
artifact_rows = []
for path in sorted(ARTIFACT_DIR.iterdir()):
    artifact_rows.append({"file": path.name, "size_mb": round(path.stat().st_size / (1024 * 1024), 3)})
display(pd.DataFrame(artifact_rows))

Artifacts directory: /kaggle/working/artifacts
Artifacts zip: /kaggle/working/object_detection_artifacts.zip
Files:

                                file  size_mb
0                           best.pth  660.639
1                        best_f1.pth  660.733
2                     best_map50.pth  660.739
3                  best_val_loss.pth  660.745
4                           last.pth  660.639
5        threshold_sweep_results.csv    0.002
6  train_history_20260611_064337.csv    0.027
7               val_predictions.json    0.375
8                     val_score.json    0.001

## 10. Summary Shown In Notebook

In [10]:
summary = {
    "best_checkpoint": str(PROJECT_DIR / "models" / "best.pth"),
    "best_map50_checkpoint": str(PROJECT_DIR / "models" / "best_map50.pth"),
    "best_val_loss_checkpoint": str(PROJECT_DIR / "models" / "best_val_loss.pth"),
    "best_f1_checkpoint": str(PROJECT_DIR / "models" / "best_f1.pth"),
    "history_csv": str(HISTORY_CSV) if HISTORY_CSV is not None else None,
    "val_predictions": str(VAL_PREDICTIONS),
    "val_score": str(PROJECT_DIR / "val_score.json"),
    "threshold_sweep_results": str(PROJECT_DIR / "threshold_sweep" / "threshold_sweep_results.csv"),
    "artifacts_zip": "/kaggle/working/object_detection_artifacts.zip",
}
print(json.dumps(summary, ensure_ascii=False, indent=2))

if HISTORY_CSV is not None:
    history_df = pd.read_csv(HISTORY_CSV)
    print("Final history row:")
    display(history_df.tail(1))

score_path = PROJECT_DIR / "val_score.json"
if score_path.exists():
    score = json.loads(score_path.read_text(encoding="utf-8"))
    print(f"mAP@0.5={score.get('mAP@0.5')} performance_points={score.get('performance_points')}")

{
  "best_checkpoint": "/kaggle/working/object-detection/models/best.pth",
  "best_map50_checkpoint": "/kaggle/working/object-detection/models/best_map50.pth",
  "best_val_loss_checkpoint": "/kaggle/working/object-detection/models/best_val_loss.pth",
  "best_f1_checkpoint": "/kaggle/working/object-detection/models/best_f1.pth",
  "history_csv": "/kaggle/working/object-detection/models/train_history_20260611_064337.csv",
  "val_predictions": "/kaggle/working/object-detection/val_predictions.json",
  "val_score": "/kaggle/working/object-detection/val_score.json",
  "threshold_sweep_results": "/kaggle/working/object-detection/threshold_sweep/threshold_sweep_results.csv",
  "artifacts_zip": "/kaggle/working/object_detection_artifacts.zip"
}
Final history row:

,run_started_at,epoch,total_epochs,train_data,val_data,image_dir,val_image_dir,image_size,batch_size,num_workers,...,val_class_loss,val_num_positive,val_map50,val_micro_precision,val_micro_recall,val_micro_f1,val_macro_f1,best_map50,best_val_loss,best_micro_f1
29,2026-06-11 06:43:37,30,30,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,/kaggle/input/datasets/duong1589/object-detect...,640,16,2,...,0.035454,211.585106,0.67155,0.854305,0.702128,0.770777,0.76115,0.681145,2.167502,0.772373

mAP@0.5=0.681145 performance_points=20